### ISSUE TITLE
[MOD] Fast Leaf Decay

### ISSUE THREAD

**Issue by postal291** [mahjerion/Craft-to-Exile-Harmony#1]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay

**Why you think it might be beneficial to Craft to Exile**
Because waiting around for saplings isn't fun.

**Comment by BBXMax** [comment]
Forge mods are not welcome here 😏

**Comment by postal291** [comment]
Alright then, add it as a datapack.

**Comment by mahjerion** [comment]
You can't really add mods as datapacks. I will add another mod that does something like this though.
