### ISSUE TITLE
[MOD] Modern Industrialization

### ISSUE THREAD

**Issue by noncom** [mahjerion/Craft-to-Exile-Harmony#10]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/modern-industrialization

**Why you think it might be beneficial to Craft to Exile**
There is an already discussed need for a tech mod.

**Additional context**
I haven't ever tried it myself, but this tech mod hasn't been yet reviewed as a possible tech mod candidate.

**Comment by mahjerion** [comment]
Just got to this. Looks like a good candidate. Will be testing this

**Comment by mahjerion** [comment]
Deciding against this. Want something a little more low-tech. Appreciate the suggestion though.
