### ISSUE TITLE
[MOD] Building Wands for Dummies

### ISSUE THREAD

**Issue by Jetx00** [mahjerion/Craft-to-Exile-Harmony#100]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/building-wands

**Why you think it might be beneficial to Craft to Exile**
Though you'd want harmony to be more in the Vanilla feel but with all the blocks available. It will help building structures easier in the server. plus it has a function to basically randomize blocks during the building phase, as shown in the mod page.

**Additional context**
Would understand if the recipe cost for the wand would be a bit expensive similar to how the danks or the bag is.

**Comment by mahjerion** [comment]
I'm usually very skeptical of these types of mods because they either impact server performance or have issues iwth modded blocks and cause crashes. Commenting to let you know I've finally taken a look and that it'll probably be on the backburner for a while. Thanks for the suggestion

**Comment by mahjerion** [comment]
closign because of performance
