### ISSUE TITLE
[BUG] Fabric Furnaces crashing with ticking player entity.

### ISSUE THREAD

**Issue by Kamisoi** [mahjerion/Craft-to-Exile-Harmony#101]
**Technical Specs (please complete the following information):**
 - Craft to Exile Harmony 2.1.1c
 - World Type: multiplayer server - Meowstard's Gaming Community server
 - RAM Allocation: 10GB [for server].

**Describe the bug**
Fabric Furnaces crash server with xp ticking player. Already posted issue at Draylar's mod issues, but wanted to leave it there too.
**Expected behavior**
Server should not crash due to ticking player with xp.

**Additional Information (screen shots, etc.)**
Link: https://github.com/Draylar/fabric-furnaces/issues/30
![image](https://user-images.githubusercontent.com/26931504/110235928-37228180-7f33-11eb-95db-61b1cac3d6ed.png)

**Comment by mahjerion** [comment]
Thanks very much for cross posting. Draylar is pretty good with this stuff so I'm sure they'll get to it soon.
