### ISSUE TITLE
[BUG] dosent launch at all

### ISSUE THREAD

**Issue by radunerd** [mahjerion/Craft-to-Exile-Harmony#102]
- Craft to Exile Version newest
 - World Type none
 - RAM Allocation 4gb

game dosent launch

1. i press play and it dosent open and its open on task manager

![image](https://user-images.githubusercontent.com/80208193/110243529-74066c80-7f63-11eb-934b-0636292c6b73.png)

**Comment by mahjerion** [comment]
Can you provide a log or something? What launchare are you using? You need to use a mod pack launcher like GDLauncher. Look at the wiki
