### ISSUE TITLE
[MOD] Inventory HUD+

### ISSUE THREAD

**Issue by beyondlife** [mahjerion/Craft-to-Exile-Harmony#103]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/inventory-hud-forge

**Why you think it might be beneficial to Craft to Exile**
I frequently lose armor to breakage. I think if the durability were on-screen, it would mitigate this somewhat. My inventory also fills up very quickly on loot runs. This would allow me to see my inventory status at a glance while trying not to die like when I'm in a battle tower. It also has a configurable display for potion buffs which could be useful.

**Additional context**

**Comment by mahjerion** [comment]
I was going to say theres something coming for durability viewing in Harmony, but i acutally think the potion display from this mod is pretty nice. Thanks. May switch them
