### ISSUE TITLE
My thoughts :D

### ISSUE THREAD

**Issue by Clugor** [mahjerion/Craft-to-Exile-Harmony#105]
It feels like a lot of non Age of exile gear is redundant. The amount of effort required to craft dragon armor for tier 40 gear is useless. Crystalite gear doesn't seem to have any difference than just making an Arcana piece with some dust and wool instead. 

Maybe incentivize those items by gauranteeing them level 50, or always epic+, etc?

Also isn't much content at max level. Outside of running around looting dungeons and towers in the overworld, breaking spawners for loot. Needs some form of rifts from d3, or maps from poe. Not enough spawners to break in the nether or End to be worth raiding.

I like the extra mobs added in the latest patch with the orks and ender knights and so on. Gives a little bit of a challenge for geared players.

If you have magic shield, and someone types in-game, their message is blocked by the hearts. Not an issue on dissonance since the UI is lower.

The idea of defending your base on crimson moons doesn't really work for the highlight of the pack. Most of the time it's just a massive amount of elemental slimes. The loot seems lower from slimes, or maybe because i'm killing so many it's lowering my drop rate in that chunk. I've gone out and went on killing sprees during crimson moons, and all i've gotten is the typical loot with a few Scarlet gems. (Maybe even just remove elemental slimes entirely, nobody would miss them)

Seeing as scarlet gems just create gear with Age of exile stats and can still proc common/low tier... Just doesn't feel like Crimson moon is enjoyable for early-game players who won't be prepared, and it doesn't quench the thirst of end-game players. Unless you can remove crimson loot dropping from normal mobs and make it a crimson moon exclusive crafted-only item that has epic+ quality, or some other form of useful reward. 

Would be cool to have a way to add the elytra to a bauble slot, maybe have it require some sort of reagent so it's harder than just "achieve elytra and slap it in ur bauble and not worry about it". 

Also hammers are VERY strong compared to any other build I've messed around with on singleplayer. They either need to be toned down, or everything else needs to be toned up to a more level field.

MRE's grant 5300 mana, enchanted golden apples grant 2k mana. Not sure if that's intended or not, but food doesn't have a healing equivilent of an MRE compared to porkchops/steak.

Just some ideas and thoughts :) Still love the pack, just getting bored at 50.

**Comment by mahjerion** [comment]
Thanks for the feedback Clugor, i'll address each point at a time.

The crafting of gear is not meant to be good. It's just a pseudo-replacement for aoe gear until you can find better aoe gear. I could make them a little better but we'll see.

End-game content, it's not a limitation of implementation it's a Fabric loader limit straight up. There is no way to add end-game content that we're looking for or I'd have added it already.

Crimson Moon is in a weird spot and I hope to work with Draylar to improve it a bit, we'll see.

Hammer nerf is already incoming!

Can't do anything about the MRE besides disabling it, may consider.

I do have stuff "planned" but tbh it's way, way down the line... THere's a HUGE Age of Exile update comign out but it's not really close to ready yet. If you're not on the AoE discord you should really check it out. It basically adds more things to do, and some end-game content
