### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PardicWanderer** [mahjerion/Craft-to-Exile-Harmony#106]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.1.1c]
 - On Launch

**Describe the bug**
When I launch the game it says that the editsign mod requires 1.16.4, and as I am playing on 1.16.5, it doesn't work.

I just ended up playing on 1.16.4

**Comment by mahjerion** [comment]
we are on 1.16.4
