### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crysis27** [mahjerion/Craft-to-Exile-Harmony#109]
**Technical Specs (please complete the following information):**
 - 2.1.1c
 - LAN
 - 8GB
**Describe the bug**
I am playing with two more friends. When they enter the world, they see blocks so bad. Like instead of a tree they see trapdoors and water, and so.

**To Reproduce**
1. Start a world
2. open it to LAN
3. Get someone to connect
4. Blocks are replaced in their games, not mine.

**Expected behavior**
Blocks should be the same to all players.

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
Hey, there are issues with LAN play.
https://github.com/mahjerion/Craft-to-Exile-Harmony/wiki/Server-Setup
I suggest setting up a dedicated server
