### ISSUE TITLE
[BUG] Kill Quest does not complete

### ISSUE THREAD

**Issue by ghostbear77** [mahjerion/Craft-to-Exile-Harmony#11]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version: 1.1.0c
 - World Type: Singleplayer, custom world Large Biomes
 - RAM Allocation: 10GB

**Describe the bug**
I killed Zombies of different types for 2 nights in a row, including Flame, Tera and Arcane Zombies, that look like recolored Drowned. The Overworld Quest "Age of Exile Mobs" to kill Arcana Zombies does not register these killings.

**To Reproduce**
1. Create new world
2. Select Human Warrior
3. Complete 2 previous quests "Just Vanilla" and "Inventory Space"
4. Kill an Arcana Zombie
5. Check Questbook for completion of Quest "Age of Exile Mobs"
6. Kill counter is still 0/1

**Expected behavior**
The Quest is completed after killing the required number (1) of Arcane Zombies

**Additional Information (screen shots, etc.)**
I replicated the bug in a "Default"-style world
Both, initial bug and replication, were found in the "Grassland Plateau"-biome at night with normal mob spawns

Edit: corrected the Mob name, "Arcana Zombie"

**Comment by Blizhazard** [comment]
I believe this is a know bug in the quest book mod, hopefully it will be fixed in the next update.

**Comment by mahjerion** [comment]
is known, will be fixed (eventually) thank you though
