### ISSUE TITLE
[BUG] MC 1.16.4 Game crash

### ISSUE THREAD

**Issue by TheDarkRisen** [mahjerion/Craft-to-Exile-Harmony#110]
**Technical Specs (please complete the following information):**
 - Craft to Exile - Version 2.1.2b
 - World Type - singleplayer
 - RAM Allocation - 6GB

**Describe the bug**
Game crash

**To Reproduce**
1. Enter New or existing World
2. Just play game 
3. Game crashes

**Expected behavior**
Just play game without crashes

**Additional Information (screen shots, etc.)**
Here is my crash-log.
[crash-2021-04-13_18.16.40-server.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/6304411/crash-2021-04-13_18.16.40-server.txt)

**Comment by Oratanias** [comment]
Hey everyone. Having the same issue. The game starts ok then I choose any world and it crashes during the loading screen just before 0% world loading info
[crash-2021-04-13_23.02.40-server.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/6306455/crash-2021-04-13_23.02.40-server.txt)

**Comment by TheDarkRisen** [comment]
You have another problem. My issue seems related with repurposed structures mod.

**Comment by TheDarkRisen** [comment]
Find this issue:
https://github.com/TelepathicGrunt/RepurposedStructures-Fabric/issues/106

**Comment by mahjerion** [comment]
Thank you @TheDarkRisen for posting. His datapack worked great, don't know why I didn't think of it earlier!
