### ISSUE TITLE
[MOD] Lambda Controls

### ISSUE THREAD

**Issue by ionstorm66** [mahjerion/Craft-to-Exile-Harmony#111]
https://www.curseforge.com/minecraft/mc-mods/lambdacontrols

Adds controller and touch screen support. I use this to play MC remotely on my phone.

**Comment by mahjerion** [comment]
I won't add this because I believe this is a client-side mod so players can add it one case-by-case basis. I want to avoid potential conflicts if possible, unless it can be confirmed that there's NO cause for concern.

Also pretty cool that you play onthe phone!

**Comment by ionstorm66** [comment]
It has a server side that allows disabling/enabling some features. They are disabled by default when connecting to a server if the server has no plugin to stop "cheating"

**Comment by mahjerion** [comment]
Good to know, thanks ion. I'll consider adding it!
