### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by freaki2010** [mahjerion/Craft-to-Exile-Harmony#112]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version from 2.1.1c to 2.1.2c
 - World Type Multiplayer
 - RAM Allocation 6GB

**Describe the bug**
After updating the Server and Client version the level progress of all the players on this server is gone.
Where can i find the level progress? I have backups from before the update.

**To Reproduce**
1. Play on old version 
2. update to new version
3. wonder why your player progress is gone :D

**Expected behavior**
After update the player progress is still there

**Comment by mahjerion** [comment]
its in the player data files, it shouldnt reset, sounds like you may have updated incorrectly.
