### ISSUE TITLE
[BUG]Won't Start

### ISSUE THREAD

**Issue by ShinigamiWolf** [mahjerion/Craft-to-Exile-Harmony#114]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.1.2c]
 - World Type [singleplayer]
 - RAM Allocation [8GB]

I installed the Modpack on Curse Forge and started it, it opens my Minecraft Launcher. After i pressed Play the Minecraft Window opens but closes immediatelyn after, opening a Window with the Message Exit-Code: 0

Does anybody else have this problem? i reinstalled the modpack, Curseforge and Minecraft multiple times now but nothing changes
![Screenshot](https://user-images.githubusercontent.com/83542442/116815114-5701aa80-ab5c-11eb-964b-aaf6d8caedf7.PNG)

**Comment by mahjerion** [comment]
reinstall the modpack, also check out the wiki for troubleshooting tips.
