### ISSUE TITLE
[BUG] nether and end portals broken (sorry for bad english)

### ISSUE THREAD

**Issue by amytori** [mahjerion/Craft-to-Exile-Harmony#118]
**Technical Specs:**
 - Craft to Exile Version [2.2.0b]
 - World Type [multiplayer]
 - RAM Allocation [server has 2650MB ]

**Describe the bug**

**To Reproduce**
1. Go to '2.0.2c go to nether/end'
2. Click on 'update to 2.2.0b'
3. try going back into the nether/end and it doesnt work

**Expected behavior**
you shouldnt be able to go to the nether after you do it. it just breaks all kinds of portals 

**Additional Information (screen shots, etc.)**
theres not much to say then that honestly. i did go into the nether with my friends before the server auto updated to 2.2.0b.
really sorry for my  bad grammar and spelling

**Comment by mahjerion** [comment]
Apologies for the long reply. The fix is to get the level seed for your world, and regenerate the level.dat file in a singleplayer world using the level seed. Then take the newly formed level.dat from the singleplayer world and overwrite the one in your multiplayer server.
