### ISSUE TITLE
Questbook missions can´t be completed[BUG]

### ISSUE THREAD

**Issue by SircuteFTS** [mahjerion/Craft-to-Exile-Harmony#119]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.2.1b
 - World Type singleplayer/multiplayer (official Server)
 - RAM Allocation 17GB

**Describe the bug**
Questbook missions can`t be completed.

- 5. Exchange -> The Philosopher´s Stone (mod Art of Alchemy)
- 3. Nether -> Blackstone Golem and Golem Daily (kill done no completion) (mod AdventureZ) 

**Expected behavior**
These two missions can´t be completed by the player´s on single and multiplayer.

**Additional Information (screen shots, etc.)**

5. Exchange
![Themissionstone](https://user-images.githubusercontent.com/83900035/119946416-e4d38880-bf96-11eb-8f26-e1fc39a5b137.png)

![Philostone](https://user-images.githubusercontent.com/83900035/119946437-eac96980-bf96-11eb-9435-ceae3f937cac.png)

3. Nether -> Blackstone Golem
Video
[https://youtu.be/w_lq4Nj3_Mo](url)

![mis_blackstone](https://user-images.githubusercontent.com/83900035/119946512-ff0d6680-bf96-11eb-828f-71622386975c.png)

**Comment by mahjerion** [comment]
Thank you, fixed for next release!
