### ISSUE TITLE
Dank Storage reset[BUG]

### ISSUE THREAD

**Issue by SircuteFTS** [mahjerion/Craft-to-Exile-Harmony#121]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.2.1d
 - World Type singleplayer/multiplayer
 - RAM Allocation 18 GB

**Describe the bug**
The Dank storage hold the Item´s only in the personal inventory or alternative storages when you put the Dank in the Dankstation the Dank are reset the complete Inventory. Tested with all Dank storages.
On a few try´s the reset when I leave the loaded chunk´s as well.

**To Reproduce**
1. Craft a Dank storage put item´s in it
2. Put into the Dank dock
3. left the server or singleplayer 
4. Join the server or single player all itme´s disappeard 

**Expected behavior**

**Additional Information (screen shots, etc.)**
1.First create a new Dank on Multiplayer and Singleplayer
![1](https://user-images.githubusercontent.com/83900035/121732642-c7ec9880-caf2-11eb-84d3-8da13fda737f.png)

2.Put into the Dankstation (we can see at the informationline the filtered button´s are gone.
![2](https://user-images.githubusercontent.com/83900035/121732853-05512600-caf3-11eb-983d-f87a331ac050.png)

3. After I reconnected on the Server M+S all items are gone.
![3](https://user-images.githubusercontent.com/83900035/121732982-2fa2e380-caf3-11eb-931a-dcaae25b4e4d.png)

**Comment by mahjerion** [comment]
i disabled the dock. not a true fix but i dont want people going through this
