### ISSUE TITLE
Epic Ore from Bee Comb not stacking with normal Epic Ore

### ISSUE THREAD

**Issue by jodyjr8** [mahjerion/Craft-to-Exile-Harmony#122]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.10.4
 - World Type multiplayer
 - RAM Allocation 10gb
**Describe the bug**

**To Reproduce**
1. Gather Epic Ore Comb
2. Stick it in a centrifuge
3. The epic ore from that will not stack with other epic ore

**Expected behavior**
I expected it to stack

**Comment by mahjerion** [comment]
Can you provide screenshots?

**Comment by mahjerion** [comment]
Also this is harmony issue tracker not dissonance..

**Comment by JaisDK** [comment]
Drop them all on the ground, should fix the stacking.
