### ISSUE TITLE
[FEEDBACK] Lightning Melee

### ISSUE THREAD

**Issue by CinderSeif** [mahjerion/Craft-to-Exile-Harmony#123]
Lightning tree, while offering good ranged damage through fusilade and spear, has little to no benefit or option to be melee. The AoE discharge skill that applies static feels out of place and hardly ever used. 

To alleviate this, having another skill that is a lightning equivalent to oceans frost blade buff would be beneficial to a possible melee lightning build. It can scale in the same way that the other skill does as well, and possibly have the following two passives tied to it:

**_Passive 1: Skill now consumes static, dealing extra damage (Same as lightning spear, but possibly lower damage due to melee build being tankier than the ranged counterpart)_**
**_Alt Passive 1: Skill now applies another static stack. This can stack with other static applies for a total of 2 stacks._**
Alt passive 1 allows melee builds to still be incentivized to throwing a spear once in a while. 

**_Passive 2: Skill now converts basic attacks into AoE._**
With this passive, this would allow chances for multiple static stacks on mobs.
**_Alt passive 2: Basic attacks send out an aoe wave, dealing melee lightning damage to those hit by it_**
A fun, mid ranged passive that changes the playstyle/engagement method of melee.

**Comment by mahjerion** [comment]
took this into accoutn stay tuned :)

**Comment by mahjerion** [comment]
also you posted this in the wrong modpack issue tracker LOL
