### ISSUE TITLE
[BUG] inventory bugged

### ISSUE THREAD

**Issue by memethief209** [mahjerion/Craft-to-Exile-Harmony#125]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - RAM Allocation [e.g. 4GB]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional Information (screen shots, etc.)**
![2021-07-05_17 36 21](https://user-images.githubusercontent.com/86956700/124451044-985e4280-ddb7-11eb-96ea-08c3744d0778.png)
![2021-07-05_17 36 25](https://user-images.githubusercontent.com/86956700/124451061-9ac09c80-ddb7-11eb-9962-085a70f2388f.png)
when i put stuff in my inventory it overlaps into the game

**Comment by mahjerion** [comment]
That's not a bug. You need to disable the GUI for it. Press ESC and go to mods and find inventory gui mod. Also from how your game looks it looks like you didn't install the mod pack through a launcher, how did you install it? Check the wiki if you're not sure what I'm talking about.
