### ISSUE TITLE
[BUG] Sometimes when using waystones with shields in your offhand will make your offhand shield disappear

### ISSUE THREAD

**Issue by zlainsama** [mahjerion/Craft-to-Exile-Harmony#126]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version : 2.2.3b
 - World Type : multiplayer
 - RAM Allocation : 4G

**Describe the bug**
Sometimes, when using waystones to teleport between locations with shields in your offhand will make said shield disappear.
The shield item is gone, me and my friend lost two unique shields in this way.
I'm not sure if this affects other items.

**To Reproduce**
1. Go to a waystone.
2. Click on the waystone with shield in your offhand.
3. Scroll down to any other registered waystone and teleport.
4. See the shield disappear or not, this seems only happen when server lags.

**Expected behavior**
No items lost when using waystones.

**Additional Information (screen shots, etc.)**
We can't reliably reproduce this issue.

**Comment by mahjerion** [comment]
fixed in next update
