### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Darkest-Traveler** [mahjerion/Craft-to-Exile-Harmony#127]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.3b]
 - World Type [e.g. Client]
 - RAM Allocation [e.g. 6GB]

**Describe the bug**
The Illuminations automatic-update is making my game crash.

**To Reproduce**
 Started new instances on GD launcher for Harmony, Illuminations notifies of the update and to restart. Restart and game won't launch.

**Expected behavior**
I expected my game to start.

**Additional Information (screen shots, etc.)**
https://pastebin.com/NHhjJLgt

**Comment by mahjerion** [comment]
should be resolved
