### ISSUE TITLE
[BUG]Curseforge saying its forge instead a fabric

### ISSUE THREAD

**Issue by CanBoy67** [mahjerion/Craft-to-Exile-Harmony#129]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.2.5b
 - World Type N/A
 - RAM Allocation 8gb

**Describe the bug**
Not really sure if this is intended or not but when I download this modpack off of curseforge it downloads as a forge modpack but I thought this was a fabric modpack

**To Reproduce**
1. Download from curseforge launcher
2. See modloader as forge-36.1.16

**Expected behavior**
It to download as fabric instead of forge

**Additional Information (screen shots, etc.)**
N/A

**Comment by Kirsha0** [comment]
There are 2 modpacks, Dissonance, and Harmony. Dissonance is forge, Harmony is fabric. Also, we recommend NOT to use curseforge, but another launcher like GDLauncher.

**Comment by mahjerion** [comment]
check the wiki installation page
