### ISSUE TITLE
Cannot find child addon  380356[BUG]

### ISSUE THREAD

**Issue by Eveofshadows** [mahjerion/Craft-to-Exile-Harmony#131]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - RAM Allocation [e.g. 4GB]

**Describe the bug**
I'm trying to install the game via curse forge and it gets about 100 mods installed in and the error 
Cannot find child addon  380356 shows up
**To Reproduce**
1. Go to curse forge 
2. Click on install

**Expected behavior**
The mod pack just wont install

**Additional Information (screen shots, etc.)**

**Comment by Cheshirsk** [comment]
Same

**Comment by mahjerion** [comment]
seems to be an issue with curseforge. shoiuld resolve on its own. if not, try another launcher

**Comment by Cheshirsk** [comment]
> seems to be an issue with curseforge. shoiuld resolve on its own. if not, try another launcher

for example? 
Cuz i dont know any place where i can download this full pack.
Its bug happens on better drops mod.
