### ISSUE TITLE
[MOD] Replace Inventory Profles with Inventory Profiles Next 

### ISSUE THREAD

**Issue by blackd** [mahjerion/Craft-to-Exile-Harmony#134]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

**Why you think it might be beneficial to Craft to Exile**
It's maintained fork of the original which have been abandoned with number of new features

**Additional context**
Full disclosure: I'm the maintainer of the fork. I'm just trying to inform people that it exist.

**Comment by mahjerion** [comment]
thanks and nice work! i've replaced it for next update but idk when it'll go live
