### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BeardedHae** [mahjerion/Craft-to-Exile-Harmony#135]
Technical Specs (please complete the following information):
 - Craft to Exile Version 2.3.1
 - World Type Multi( Harmony Official)
 - RAM Allocation 8GB

Quest log is marking quests as complete, but not allowing collection of rewards. No claim reward button present. Specifically one that should be complete but will not allow me to select a "choose one" reward and claim is the enchantment table/ grindstone quest. Others in the exchange portion of quest log just auto-complete with no reward and is allowing me to progress down the quest tree as if they are full completed.

**Comment by mahjerion** [comment]
should be fixed for next update
