### ISSUE TITLE
Question about the block.ttg_fallfest.cursed_spawner

### ISSUE THREAD

**Issue by MicorIce** [mahjerion/Craft-to-Exile-Harmony#136]
I would like to ask if this block does not summon monsters after it is turned on, the progress bar has been stuck on the screen, how do I restart it?

![Inked2022-01-23_20 05 49_LI](https://user-images.githubusercontent.com/98261316/150677644-88a99ab5-a3f2-4a7b-82e6-22f132ff50ba.jpg)

**Comment by mahjerion** [comment]
duplicate #76 

hopefully answers your q, but basically no fix unfort. you can't die or leave premise once you start those or they fail forever
