### ISSUE TITLE
[BUG] CRASH

### ISSUE THREAD

**Issue by DemaxioN** [mahjerion/Craft-to-Exile-Harmony#137]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [2.3.2]
 - World Type [LAN]
 - RAM Allocation [8GB(5 for mincraft)]

**Describe the bug**
Just crash when play (random time)

Crast report :
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/30/22 3:44 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at net.minecraft.class_1140.method_4857(class_1140.java:221)
	at net.minecraft.class_1140.method_20185(class_1140.java:183)
	at net.minecraft.class_1144.method_18670(class_1144.java:249)
	at net.minecraft.class_310.method_1574(class_310.java:1566)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at net.minecraft.class_1140.method_4857(class_1140.java:221)
	at net.minecraft.class_1140.method_20185(class_1140.java:183)
	at net.minecraft.class_1144.method_18670(class_1144.java:249)

-- Affected level --
Details:
	All players: 2 total; [class_746['Slonik_Bosss'/461, l='ClientLevel', x=-251.45, y=42.00, z=-80.92], class_745['DemaxioN'/1268, l='ClientLevel', x=-278.30, y=52.00, z=-96.55]]
	Chunk stats: Client Chunk Cache: 121, 50
	Level dimension: minecraft:overworld
	Level spawn location: World: (-192,74,-48), Chunk: (at 0,4,0 in -12,-3; contains blocks -192,0,-48 to -177,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 24798 game time, 24798 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2962145256 bytes (2824 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 4
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx5117M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 1.14.2+1.16.5
		adventurez: AdventureZ 1.2.6
		allure: Allure 1.2.8
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin mc1.16.4-2.1.3
		architectury: Architectury 1.25.36
		artofalchemy: Art of Alchemy: Memoriam 1.1.0+1.16.5
		audiooutput: AudioOutput 0.0.3
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		balance_of_exile: Balance of Exile 1.0.5
		bclib: BCLib 0.1.45
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterdungeons: YUNG's Better Dungeons 1.16.5-1.0.1
		betterend: Better End 0.9.8.5-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betternether: Better Nether 5.0.7
		betterpingdisplay: Better Ping Display 1.1
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		betterthirdperson: Better Third Person 1.5.0
		biome_locator: Biome Locator 1.1.2
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.3-1.16.5
		byg: BYG 1.3.5
		campanion: Campanion 1.3.5
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		cavebiomes: Cave Biomes 0.6.2
		charm: Charm 2.3.2
		charmonium: Charmonium 2.3.2
		chas: Craftable Horse Armour & Saddle 1.16-1.7-Fabric
		chat_heads: Chat Heads 0.5.1
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.4.0
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.5.57
		cloth-api: Cloth API 1.5.50
		cloth-armor-api-v1: Cloth Armor API v1 1.5.50
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.50
		cloth-common-events-v1: Cloth Common Events v1 1.5.50
		cloth-config-lite: cloth-config-lite 1.0.4
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.5.50
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.50
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.5.50
		cloth-scissors-api-v1: Cloth Scissors API v1 1.5.50
		cloth-utils-v1: Cloth Utils v1 1.5.50
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.3.0
		controlling: Controlling For Fabric 1.1.2
		craftpresence: CraftPresence 1.8.8
		creeperspores: Creeper Spores 1.5.0
		curios: Curios API 0.0.13-1.16.5
		dankstorage: Dank Storage 1.10a-1.16.5
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		dragonloot: DragonLoot 1.0.6
		dungeons_arise: When Dungeons Arise 1.16.5-2.1.47-fabric
		dungeons_of_exile: Dungeons of Exile 1.1.1
		dynamicfps: Dynamic FPS 2.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		dynamo_api: Dynamo API 1.0.0+1.16
		editsign: EditSign 2.2.1
		enchdesc: EnchantmentDescriptions 2.0.8
		endreborn: End: Rebellion 1.8
		engilib: EngiLib 1.0.0+1.16
		enhancedcelestials: Enhanced Celestials 2.0.5
		entityculling: EntityCulling-Fabric 1.3.0
		fabric: Fabric API 0.35.0+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.1.0+731c05f37d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.10+3661eaa17d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+0ef801b67d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricloader: Fabric Loader 0.12.12
		fallflyinglib: FallFlyingLib 1.1.0
		fancymenu: FancyMenu 2.4.0
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.4
		fatxporbs: Fat Experience Orbs 0.0.9
		ferritecore: FerriteCore 2.1.0
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		flan: Flan 1.16.5-1.6.3
		flesh2leather: Flesh2Leather 1.0.2
		flytre_lib: FlytreLib 0.2.11
		geckolib3: Geckolib 3.0.58
		go-fish: Go Fish 1.2.3-beta-1.16.5
		gottaclimbfast: Gotta Climb Fast! 1.0
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		hardcorequesting: Hardcore Questing Mode 1.16.5-5.5.12
		heartbond: Heartbond 1.0.0
		hypnos: Hypnos 0.1.1
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.5.1
		inmis: Inmis 2.2.1-1.16.5
		inventoryhud: Inventory HUD + 3.4.0
		inventoryprofilesnext: Inventory Profiles Next 1.2.1
		invtrashslot: InvTrashSlot 1.0.2
		ironchest: Iron Chests 1.0.0+fabric-1.16.5
		itemflexer: ItemFlexer 1.1.4
		itemscroller: Item Scroller 0.15.0-dev.20210111.205029
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		konkrete: Konkrete 1.3.0
		kubejs: KubeJS 1605.3.19-build.184
		kyrptconfig: Kytpt Config 1.1.4-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.8.8
		libblockattributes_core: LibBlockAttributes (Core) 0.8.8
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.8
		libblockattributes_items: LibBlockAttributes (Items) 0.8.8
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		library_of_exile: Library of Exile 1.0.7
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.8.1
		lithium: Lithium 0.6.6
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		malilib: MaLiLib 0.10.0-dev.21+arne.5
		maybe-data: Maybe data 1.0.0-1.16.2
		mechanicaltech: Mechanical Tech 0.3.0+1.16
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		microconfig: Microconfig 1.1.0
		mimics: Mimics 0.1.4
		minecraft: Minecraft 1.16.5
		mmorpg: Age of Exile 1.7.13
		modmenu: Mod Menu 1.16.22
		mostructures: Mo' Structures 1.2.0-1.16.5
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		musicdr: Music Duration Reducer 1.2.0
		nbtcrafting: NBT Crafting 2.0.5+mc1.16.4
		omega-config: OmegaConfig 1.0.4
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 19.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		origins: Origins 0.7.3
		origins-classes: Origins: Classes 1.1.1
		patchouli: Patchouli 1.16.4-53-FABRIC
		petowner: Pet Owner 1.8.0-1.16.5+
		phosphor: Phosphor 0.8.0
		polymorph: Polymorph 0.0.13-1.16.5
		randompatches: RandomPatches 2.4.5-fabric
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		rhino: Rhino 1605.1.5-build.75
		roughlyenoughitems: Roughly Enough Items 5.12.248
		roughlyenoughitems-api: REI (API) 5.12.248
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.248
		roughlyenoughitems-runtime: REI (Runtime) 5.12.248
		roughlyenoughresources: Roughly Enough Resources 2.1.5
		satin: Satin 1.5.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.3
		terrestria: Terrestria 2.2.0
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.4.11-fabric
		tlskincape: TLSkinCape 1.19
		trade: Trade 1.1.3
		transferchestmod: Transfer Chest 1.1.4
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.3
		ttg_fallfest: FallFest 2020 0.1.1
		vanilladeathchest: VanillaDeathChest 2.0.6-fabric
		voyager: Voyager 1.0.0
		ward_blocks: Ward Blocks 1.0.21
		waystones: Waystones 2.0.1
		whereisit: Where Is It 1.11.7
		wildworld: Wild World 2.0.0+1.16.5
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		wthit: wthit 2.10.9
		xaerominimap: Xaero's Minimap 21.22.3
		xaeroworldmap: Xaero's World Map 1.18.6
		xp_storage: XP Storage 1.4+1.16.5
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.5-Fabric-9
		zoob: Monster Of The Ocean Depths 3.0.0
	Patchouli open book context: n/a
	Launched Version: Fabric 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon HD 5450 GL version 4.5.13417 Compatibility Profile Context 15.301.1901.0, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla
	Current Language: Русский (Россия)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz

**Comment by mahjerion** [comment]
tbh i dont really know, looks like an unfortunate random crash
