### ISSUE TITLE
[BUG]About the element resistent and damage reduction

### ISSUE THREAD

**Issue by TUsama** [mahjerion/Craft-to-Exile-Harmony#138]
**Technical Specs (please complete the following information):**
 - Craft to Exile 2.15.1
 - World Type: any situations

**Describe the bug**
I prefer to give the steps which could show the thing making me confused, because I'm not sure whether is a bug, or it's designed on purpose.

**To Reproduce**
1. create a new world
2. level you up in oeder to get enough talent and stats points.
3. then check out your spell damage of each element.
4. open the talent GUI, allocate your talent like this: 

[![b15sqs.png](https://s4.ax1x.com/2022/03/02/b15sqs.png)](https://imgtu.com/i/b15sqs)

5. check out your spell damage of each element, that should be 0 now.
6. allocate the stats point at int, at least got 1% elemental spell damage.
7. check out your spell damage of each element, it should now be the value of element resistent.
8. also this can work on the all elemental damage and spell damage.

my point is, It's a bug or something that the element resistent can increase damage. Honestly, If you allocate every element resistent talent, it can makes your stats incredible high. This can truly break the game balance.

And the damage reduction is a balance breaker too. If you got it from gears or runeword etc., mobs can hardly damage you, even you only have like 5% damage reduction(this is my damage reduction stats value, In a server).

As for now, we are suffering the balance problem made by these. Hoping for your reply!

**Comment by mahjerion** [comment]
isnt this the wrong issue tracker?

**Comment by TUsama** [comment]
oh sorry for that, I should open this issue in the Dissonance repo.
