### ISSUE TITLE
[FEEDBACK] Wraiths are extremely rare, taking away from the fun of the modpack

### ISSUE THREAD

**Issue by GeorgeEBeresford** [mahjerion/Craft-to-Exile-Harmony#139]
**Is your feature request related to a problem? Please describe.**
Wraiths seem almost impossible to find. It took my friend and I about 2 weeks before we found our first wraith. I know a few others have the same issue. 

**Describe the solution you'd like**
Increase the spawn weight of the Wraith mob

**Describe alternatives you've considered**
Change the quest to something a little more fun. On my own server (that uses this modpack), I went ahead and changed the quest rather than having my friend and I burn out and stop playing. (I'm aware the quest is basically just a repeat of Prelude: Feral Creatures lol)
![image](https://user-images.githubusercontent.com/17858167/156822762-daab8a69-3f72-446b-8f22-5f5370d97b59.png)

**Additional context**
I don't mind killing a hard mob or killing lots of weak mobs as you have some degree of control over the progress; searching for a mob that may or may not spawn isn't very fun, especially as it blocks progress to the rest of the quest line.

**Comment by mahjerion** [comment]
wrong modpack lol, was wondering where this went

**Comment by mahjerion** [comment]
resolved in next update
