### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TheLittleCube** [mahjerion/Craft-to-Exile-Harmony#14]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version : 1.1.0c
 - World Type : Multiplayer
 - RAM Allocation : 8G

**Describe the bug**
Perk - Flicker:
 Doesn't apply on hit damage

**To Reproduce**
1. Level up to and rush perks to Flicker skill
2. Use skill on mob/player Teleport
3. Skill does not apply on hit Effects/Radius 

**Expected behavior**
Flicker should apply 1+50%(Weapon Attack Physical Damage) upon teleporting to mob/player in the Area of Effect.

**Comment by mahjerion** [comment]
Thanks I'll take a look.

**Comment by mahjerion** [comment]
It does do damage, radius might have been too low? I'm also not sure if it does damage upon landing or upon activation (before/after the tp), but it does work!
