### ISSUE TITLE
Complete darkness [BUG]

### ISSUE THREAD

**Issue by ArcaneRay14** [mahjerion/Craft-to-Exile-Harmony#15]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [1.1.0c]
 - World Type [Singleplayer]
 - RAM Allocation [ 8GB]

**Describe the bug**
Everything becomes extremely dark including your surrounding, hotbar , menu and JEI comes nightime and light sources don't work

**To Reproduce**
1. Create new world
2. pick Feline origin / nitwit class
3. wait till nighttime
4. everything should become dark and torches don't work

**Expected behavior**
My theory is that the Feline class with the nocturnal advantage is causing this bug to happen because nocturnal allows to see a little better at night time which may be the reason for the visual bug any sort of light do not work

**Additional Information (screen shots, etc.)**
![Screenshot (46)](https://user-images.githubusercontent.com/72735660/95732544-8ec10780-0c89-11eb-8d05-71b7dec9d044.png)

**Comment by mahjerion** [comment]
Hm.. very odd. Have you cross-posted to Origins issue tracker?

**Comment by mahjerion** [comment]
Hey actually, try removing the mod Blur and see if that fixes it!

**Comment by mahjerion** [comment]
Realized I don't even have the feline race. This isn't something I need to fix. But it's probably because of blur
