### ISSUE TITLE
[BUG] the mob killing quests dont seem to register in the quest book

### ISSUE THREAD

**Issue by ImelchorI** [mahjerion/Craft-to-Exile-Harmony#16]
- Craft to Exile Version [e.g. 1.1.0c]
 - World Type: singleplayer

pretty much the title. anything related to killing mobs, including specific mobs doesnt seem to register in the quest book.

for example i killed a bunch of terra spiders, and the counter for the daily quest to kill terra mobs in chapter 1 of the book is still on 0 of 10 on the spiders.

same seems to be the case for vanilla mobs, the arcana zombie etc.

**Comment by mahjerion** [comment]
it's a known issue, and has been fixed in later version
