### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AminoX99** [mahjerion/Craft-to-Exile-Harmony#17]
**Technical Specs (please complete the following information):**
 -CrafttoExile-Harmony-1.2.0
 - RAM = 4 gb

**Describe the bug**
The game doesn't start, it crashes saying a a mod requires 1.16.2 version.

**To Reproduce**
1. Download version 1.2.0 of the modpack
2. Click on play
3. Crash

**Expected behavior**
I expect the game to run without problems
**Additional Information (screen shots, etc.)**
![help](https://user-images.githubusercontent.com/69323478/96136977-583ef300-0efc-11eb-9aeb-b8294c56b842.PNG)

**Comment by mahjerion** [comment]
did you try reinstalling it

**Comment by AminoX99** [comment]
I didnt need to, because somebody on discord helped me with changing the mod versions to 1.16.3, now it works perfectly, thanks for making this modpack, I really wanted to play something like this
