### ISSUE TITLE
[BUG] Portals to Nether/Nether is broken

### ISSUE THREAD

**Issue by Magesw** [mahjerion/Craft-to-Exile-Harmony#18]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version **1.2.0/1.2.1**
 - World Type **Multi**
 - RAM Allocation **10G**

**Describe the bug**
Since v 1.2.0 of CtE [Harmony] the Nether/Nether portals to the Nether are now broken, standing in a portal will not TP you to the Nether. Even the *Official* server portals are broken.

**To Reproduce**
1. Start any 1.2.0/1.2.1 game and attempt to step into a Nether portal.

**Expected behavior**
When I step into a Nether portal I expect to be TPed to the Nether

**Additional Information (screen shots, etc.)**
N/A

**Comment by mahjerion** [comment]
Interestinggggg. Can you provide a log of when you try to access the Nether?

**Comment by mahjerion** [comment]
Weird, it worked on my end in SP

**Comment by Magesw** [comment]
> Weird, it worked on my end in SP

I didn't mention SP, on both the official server and mine the Nether is broken. I watched the console as I attempted to enter on mine and nothing shows. Deleting the Nether and restarting the server to have it make a new one didn't even work, it just doesn't create one.

**Comment by mahjerion** [comment]
Hey thanks, so I noticed this too when testing, it worked for me on my own server but not the official as well... So weird. I'll keep looking around and will update this issue if I figure it out.

**Comment by Gpauxe** [comment]
Can confirm is happening on my private server as well

**Comment by mahjerion** [comment]
Thanks @Gpauxe ill have to test probably with the official server since its the only way for my to recreate it. Unless one of you would be kind enough to help me test this - pm me :D

**Comment by mahjerion** [comment]
I've tested this by removing and readding every mod I added recently... It's possible the latest update simply bugged worlds. Is it happening on _new_ worlds too or just your existing ones?

**Comment by Magesw** [comment]
> I've tested this by removing and readding every mod I added recently... It's possible the latest update simply bugged worlds. Is it happening on _new_ worlds too or just your existing ones?

I just started a new world on my server and the portal worked.

**Comment by Magesw** [comment]
> Unless one of you would be kind enough to help me test this - pm me :D

I am happy to help.

**Comment by mahjerion** [comment]
Thanks so much! That confirms it - one of the new mods basically corrupted the Nether... Was hoping regenerating the Nether would fix it.

While it's good I know what caused it... This is really bad news lmao. Will consider what to do with the current official server... Thanks a lot @Magesw !

**Comment by TheLittleCube** [comment]
Found a fix. Nether and End Generation settings are removed in the Level.dat
Steps
1. Create a new world with the same seed
2. Copy the auto generated level.dat/level.dat (old) from the copied seed
3. Delete the level.dat/level.dat (old) from your current save 
4. Paste the new level.dat in
5. ???

sorry for the re-open. Just offering a fix for those that need it.

**Comment by mahjerion** [comment]
Bless, you're a genius. Will share this on the announcements!

**Comment by mahjerion** [comment]
Repoening for visibility

**Comment by mahjerion** [comment]
closing!
