### ISSUE TITLE
Multiplayer error

### ISSUE THREAD

**Issue by TiseNowsky** [mahjerion/Craft-to-Exile-Harmony#19]
Incomplete set of tags received from server. Even after installing a fix it occours.

**Comment by mahjerion** [comment]
Can you provide a log, or at least a screen shot of the screen when this happens?

**Comment by TiseNowsky** [comment]
![image](https://user-images.githubusercontent.com/68903921/96272132-f8b11800-0fcd-11eb-9309-0f8256a8e810.png)

**Comment by TiseNowsky** [comment]
![image](https://user-images.githubusercontent.com/68903921/96272219-1b433100-0fce-11eb-83f3-9153520ab6d2.png)

**Comment by TiseNowsky** [comment]
![image](https://user-images.githubusercontent.com/68903921/96272281-30b85b00-0fce-11eb-9a04-ba58e19aa87e.png)

**Comment by mahjerion** [comment]
Still persists on the latest version?

**Comment by mahjerion** [comment]
Apparently has to do with using the wrong jar file

**Comment by abensur** [comment]
im having the same issue, fresh install from here https://www.curseforge.com/minecraft/modpacks/crafttoexileharmony/files/3130410
