### ISSUE TITLE
[BUG] No JEI recipe for wool tarp

### ISSUE THREAD

**Issue by postal291** [mahjerion/Craft-to-Exile-Harmony#2]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version Harmony 1.0.1
 - World Type singleplayer
 - RAM Allocation 8GB

**Describe the bug**
Was trying to make a sleeping bag, but there's no recipe in JEI for wool tarp.

**Additional Information (screen shots, etc.)**
Still able to craft it, had to look up the recipe on their mod page.

**Comment by mahjerion** [comment]
This is probably because of how their recipe works using shears. Can you cross post this to their issue tracker?
