### ISSUE TITLE
HQB no requirement on one quest[BUG]

### ISSUE THREAD

**Issue by Legatonin** [mahjerion/Craft-to-Exile-Harmony#20]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - RAM Allocation [e.g. 4GB]

**Describe the bug**
No requirements for this part of the book

**To Reproduce**
1. Go to '...' Quest book
2. Click on '....' The Exchange tab
3. Scroll down to '....' Unique Item Loot Crate

**Expected behavior**

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/28191018/96359111-70ec1a80-1141-11eb-9260-5c2b741998f6.png)

**Comment by mahjerion** [comment]
Thanks fixed in next version!
