### ISSUE TITLE
Skill tree is very laggy[BUG]

### ISSUE THREAD

**Issue by Legatonin** [mahjerion/Craft-to-Exile-Harmony#21]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - RAM Allocation [e.g. 4GB]

**Describe the bug**
When going to the Skill Tree in the Main Hub, it's very laggy when trying to move around the skills

**To Reproduce**
1. Go to '...' 'H' Main hub
2. Click on '....' Skill Tree
3. Scroll down to '....' anywhere and it's very laggy in there.

**Expected behavior**

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
Thanks again for the post! This is on age of exile's side and I believe the author has already fixed it (unreleased). Will close this because I can't do anything bout it!
