### ISSUE TITLE
[MOD] Change out MyCommands for Gunpowder Teleport

### ISSUE THREAD

**Issue by Magesw** [mahjerion/Craft-to-Exile-Harmony#22]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/gunpowder-teleport

**Why you think it might be beneficial to Craft to Exile**
We are already using the Gunpowder API for the sleep vote so why not just use this for /home /tpa, ect instead of MyCommands which is really broken. 
 
**Additional context**
On my server half the time the /home command won't work or it TP's you to a random person's home instead of your own with MyCommands. Let's give Gunpowders a try instead.

**Comment by mahjerion** [comment]
i only added mycommands for tpa - how configurable is gp-teleport? I'd like to only enable tpa.

**Comment by Magesw** [comment]
> i only added mycommands for tpa - how configurable is gp-teleport? I'd like to only enable tpa.

Since you have Player Roles installed you can just use Player Roles to deny any other commands it has like /sethome, /home, ect.

TheLittleCube and I have setup a server where I removed MyCommands and only use gp-teleport, it works how you want it to.

**Comment by mahjerion** [comment]
That's true, forgot I had player roles. Thanks I will do this
