### ISSUE TITLE
[BUG]Craft with chest

### ISSUE THREAD

**Issue by Rem-02** [mahjerion/Craft-to-Exile-Harmony#23]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 1.2.1
 - World Type multiplayer
 - RAM Allocation 4GB

**Describe the bug**
Craft that use chests (except hopper) can only be done using in world generated chests.
This is due to charm's chests overriding vanilla chests. 

**To Reproduce**
1. Craft a chest
2. Try to craft an iron chest with this chest

**Comment by mahjerion** [comment]
Thanks, fixed in next version
