### ISSUE TITLE
[BUG] Respawnable pets

### ISSUE THREAD

**Issue by Rem-02** [mahjerion/Craft-to-Exile-Harmony#24]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 1.2.1
 - World Type singleplayer/multiplayer
 - RAM Allocation 4GB

**Describe the bug**
Etheric Gem from Respawnable pets does not work in survival mode.
It work only in creative mode.

**To Reproduce**
1. Left click on a tamed wolf with a Etheric Gem.

**Additional Information (screen shots, etc.)**
The main difference between creative and survival is that you can hit tames wolves in creative mode.
This seems to be a conflict with another mod that prevent hitting your own pets.

**Comment by mahjerion** [comment]
Will probably remove Respawnable pets for now in this case. Thanks for posting
