### ISSUE TITLE
[BUG] Crash upon using Heavy Strike on any Cow

### ISSUE THREAD

**Issue by sileo-P** [mahjerion/Craft-to-Exile-Harmony#25]
**Technical Specs**
 - Craft to Exile Version - 1.2.2b
 - World Type - Singleplayer
 - RAM Allocation [e.g. 6GB]

**Describe the bug**
Using Heavy Strike on a level 4 Flaming Cow caused an immediate hard freeze/crash.
Weapon is starter Stick Sword obtained from the first quest.

**To Reproduce**
1. Unlock the Heavy Strike skill.
2. Using a melee weapon, right click on a cow within melee range with Heavy Strike selected.
3. The game window will either close immediately or freeze and stop responding. The freeze appears to be more common.

**Expected behavior**
The cow should take damage from Heavy Strike and the game should not crash.

**Additional Information (screen shots, etc.)**
Playing as Guardian at level 2 with all points into strength.
Using this resource pack: https://github.com/bradleyq/1_16_shaders/releases/tag/v2.2.1

[crash-2020-10-22_13.05.50-client.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/5422781/crash-2020-10-22_13.05.50-client.txt)

**Comment by mahjerion** [comment]
fixed in new version
