### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Doomsdayguy678** [mahjerion/Craft-to-Exile-Harmony#26]
The bug was when right-clicking using a heavy strike on a creature from behind while using the assassin class would crash the game.
I am not sure why this happened because it seems to only happen every once and a while.
[crash-2020-10-21_18.13.25-client.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/5425142/crash-2020-10-21_18.13.25-client.txt)

**Comment by mahjerion** [comment]
thanks already fixed! but i appreciate the report
