### ISSUE TITLE
Crashing when right clicking on a cow with the Lightning Totem spell equipped[BUG]

### ISSUE THREAD

**Issue by BigfootBravo** [mahjerion/Craft-to-Exile-Harmony#27]
**Technical Specs:**
 - Craft to Exile Version = Harmony, 1.2.2b
 - World Type = Singleplayer
 - RAM Allocation = 8 gb

**Describe the bug**
When right-clicking on a cow with the Lightning totem spell equipped, it immediately crashes the game.

**To Reproduce**
1. Go to a cow
2. Right-click on the cow, while the lightning totem spell is equipped in spells and nothing, is held in hand, torch in offhand.
4. See the error, aka, crashing

**Expected behavior**
Nothing.
**Additional Information (screen shots, etc.)**
The Mini Crash Report:

                                                    "The game crashed whilst unexpected error
                                                      Error: java.lang.StackOverflowError: Unexpected error
                                                      Exit Code: -1"
Full Crash report is linked below
[Crash Report.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/5427329/Crash.Report.txt)

I was trying to tame one of the horses in a village's pen.  A cow was in the pen as well and while clicking on the horses, I accidentally right-clicked the cow, thus crashing my game.

**Comment by mahjerion** [comment]
Awesome, ty for the detailed report. This should be fixed in 1.2.3b so try updating!

**Comment by BigfootBravo** [comment]
Wow, thanks for the fast fix!
