### ISSUE TITLE
[BUG] Can't Equip Ring

### ISSUE THREAD

**Issue by Ynirion** [mahjerion/Craft-to-Exile-Harmony#29]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - RAM Allocation [e.g. 4GB]

**Describe the bug**
There is no UI to put the ring on

**Expected behavior**
Should have some slot on the left?

**Additional Information (screen shots, etc.)**
https://i12.servimg.com/u/f12/11/01/62/44/bug_ui10.png

**Comment by mahjerion** [comment]
Thank you, issue has been fixed in next version
