### ISSUE TITLE
Harmony 1.2.6 [FEEDBACK]

### ISSUE THREAD

**Issue by SpeedyEL** [mahjerion/Craft-to-Exile-Harmony#31]
### Hello mahjerion, here is my feedback about your modpack called "Harmony" in version 1.2.6 that i have played for at least 2  weeks. ###

- Everything said down below is mostly what tickles me the most / features i would like to see.
It's only my personal opinion of course but it's also what i want "as a player"

- I always try and think about how someone would react if he/she get these before writing suggestions / ideas.

Let's begin:

**Tower dungeons:**

- Final floor, The golem boss is attacked and pushed outside the tower by any hostile mob.

- The locked chest that needs a silver key, dropped by the Golem boss. Is ridiculously unrewarding. No weapon, no armor, no rune, no "gem socket", nothing around Age of exile. Even at level 18, you still get 3 charcoals and wheat from opening this chest.

- Final boss (Golem): From my personal experience, too easy to counter, place water or let him get pushed into an ocean and fight him, he's nearly stuck when in contact of water, his projectiles are fine and can be countered.

**Skill tree:**

- Ring of fire: Channeled attack. Ticks 3 times. 
Problem: Is canceled if you try to attack.
Idea: Make it passive with a cast time. So we can attack and burn people around us.

- Heavy strike, Ground slam, Cleave:
Problem: Do the same thing with the same animation.
Problem 2: Once one of these spell is on cooldown it's impossible to hit anyone until it's fully recharged.

**These ideas can be used as "Upgrades" in the Skill tree or as "Talents."**

- Idea 1: Heavy strike: More cooldown time but increase the damage output.

- Idea 2: Heavy strike: More cooldown time but reduces the target armor by: minus 15%~30% (Between these numbers).

- Idea 3: Ground slam: Push back enemies (further) and adds a temporary slow movement by: 25%.

- Idea 4: Cleave: base damage to the receiver but deals twice as much for any enemies around the target.

- Idea 5: Tank specification:
- New spell: ( Passive ) Buckler: Block and nulify one attack every 20s, while active 50% less mana. Use the spell again to remove it's effects.
- New spell: ( Active ) Guardian: Target a player to grant him 15%~30% of your own armor for a determined amount of time. While active, you lose the same amount of armor.
- New spell: ( Passive ) Reflect: Reflect 5%~20% damage to the attacker. While active: Loses the same amount of percentage for health regen or armor.

**Classes**

Classes in Harmony is one of the most important choice to do, it will completely change your playstyle and choices for the whole game.

So far in my opinion and from what i have tested.

- Champion, Guardian, Elementalist, are one of the best classes and easiest one. You get bonuses and almost no bad side on each. One has no bad side and only bonuses, One has a free 9 slot inventory that is super safe from death with bonus enchanting, bonus shield movement, free armor without armor. The last one is okay, the bonus while in water is super cool and nice, the bonus damage when on fire is kinda weird, poison immunity is pleasant when eating rotten food and fighting witches.

- Assassin:
Is not assassin, what i would do / like to see, is an actual sneaky playstyle where if you crouch for 10s you are completely invisible with nightvision, so it actually make sense about "entering the shadow". 
I would keep the extra damage and bonuses from the actual version, but it needs some tweak.

- Deadeye:
 i don't have anything to complain or changes for this one, but what i would *LOVE* to see is a key for climbing, im only talking about personal experience but i couldn't stand the fact that you try to climb litteraly every blocks added with the mod Gotta Climb Fast! it make this class one of the worst i tried, you have to look at the very top or very down to actually climb and it's painful. 

- Didn't tried any more classes because of all the above, they seems appealing with their bonuses and the rest seems to be under those? That's only my feelings about them, Pathfinder is pretty unique, he's vegan and can have a lot of bonuses for his tammed pets, too bad there is no "necromancy" spell or talent about that.

If you would like to contact me or have more details about whatever i said above, my name is Speedy in your discord channel.
I apologize if my english is average, I try my best.

I might do another feedback if i get any other ideas or suggestions.

PS: Keep going. Love your modpack.

**Comment by mahjerion** [comment]
Thanks for the great feedback! I'll go through each of your points individually.

Tower: this isn't up to me, it's up to the mod author. But he's fixed this indev already. Thanks!

Skill Tree: it's a channel skill so how it works is intended, you shouldn't be able to cast while attacking. As for the melee skills - they're definitely a bit lack luster. I put them together relatively quickly so I'll def work on sprucing these up a bit. I like your spell ideas for the tank and augments for the physical spells. Thank you!

Classes: can't comment much since i just changed them, but I did take your feedback into consideration. let me know what you think

**Comment by mahjerion** [comment]
thanks, ended up referring to your feedback a few times when thinking about class and spell balance!
