### ISSUE TITLE
[MOD]

### ISSUE THREAD

**Issue by TheFlieb** [mahjerion/Craft-to-Exile-Harmony#32]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/armor-visibility/files

**Why you think it might be beneficial to Craft to Exile**
Simple toggle button to show armor or not

**Additional context**

**Comment by mahjerion** [comment]
This mod isn't available for our version of Fabric. Also it's client side only so you could probably just install and try it
