### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CyberFIowey** [mahjerion/Craft-to-Exile-Harmony#34]
![2020-11-13_07-58-17](https://user-images.githubusercontent.com/66869211/99034838-223e6e80-258f-11eb-9f5b-55f577bfb3da.png)

**Comment by mahjerion** [comment]
you need internet while loading with jumploader. also next time pleae provide more details rather than just one screen shot!

**Comment by CyberFIowey** [comment]
I have Internet access
