### ISSUE TITLE
[BUG] Harmony server continually crashing

### ISSUE THREAD

**Issue by maegae** [mahjerion/Craft-to-Exile-Harmony#35]
**Technical Specs (please complete the following information):**
- Harmony Version 1.3.1
- 4 GB RAM Allocation
- Multiplayer

**Describe the bug**
Recently my small friend server has been crashing a bit. It kicks players out with a "StackOverflow" error and the server stops with the "exception in server tick loop" error.

**To Reproduce**
There doesn't seem to be a pattern to it. It started when my friend tried to equip armor and he crashed every time he attempted to. I forced it on him with a dispenser and that crashed the whole server. I reset the configs because I attempted to make a custom origin, so I figured that was what was causing the crashes. After that though, the same error happens randomly. Whether someone's fighting in a raid or just walking around and exploring.

**Expected behavior**
The server not crashing.

**Additional Information (screen shots, etc.)**
First crash (before config reset): https://pastebin.com/yMZhdkYd
Recurring crashes: https://pastebin.com/Xk1CJf8Z

**Comment by mahjerion** [comment]
hm... im not sure - this crash is a little odd, if you have other reports please send them my way. ive never seen this
