### ISSUE TITLE
[BUG] Art of Alchemy does not support Sodium

### ISSUE THREAD

**Issue by firegodjr** [mahjerion/Craft-to-Exile-Harmony#37]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version: 1.3.3
 - World Type: N/A
 - RAM Allocation: N/A

**Describe the bug**
Art of Alchemy (at least under the current default configuration) is incompatible with Sodium, causing missing texture errors when placing Essentia conduits

**To Reproduce**
1. Place an Essentia conduit

**Expected behavior**
Essentia conduits should not appear as missing texture blocks

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
Was wondering what was causing this - i'll remove sodium in the mean time. thank you
