### ISSUE TITLE
[BUG] Dark Theme for LibGUI ruins the appearance of Art of Alchemy GUIs

### ISSUE THREAD

**Issue by firegodjr** [mahjerion/Craft-to-Exile-Harmony#38]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 1.3.3
 - World Type N/A
 - RAM Allocation N/A

**Describe the bug**
Art of Alchemy GUIs have very nice background images that are designed to blend in with the default Minecraft UI colors. However, the default config for LibGUI in [Harmony] is set to dark theme, which breaks the intended appearance of these GUIs.

**To Reproduce**
1. Open any Art of Alchemy GUI (Calcination Furnace, Alchemist's Journal, etc)

**Expected behavior**
The Art of Alchemy GUIs should be displayed correctly

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
oh huh, good to know. Thanks this is great feedback (not really a bug) - i'll prob change it back
