### ISSUE TITLE
[MOD] Add Inventory-profiles

### ISSUE THREAD

**Issue by spdkils** [mahjerion/Craft-to-Exile-Harmony#40]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles

**Why you think it might be beneficial to Craft to Exile**
The charm sorting button doesn't work with IRON chests, the default "big" storage in this game. Inventory Profiles is client side, and does work with that. It also supports moving same items into the chest, and many other buttons, that make game play simpler, and the typical modded minecraft inventory nightmare more controllable.

**Additional context**
You would need to disable the tidy inventory button in Charm, it also has a slight overlap with the GIANT inventory crafting button in charm, but that is tolerable.

**Comment by mahjerion** [comment]
How does this work with Dank though?

**Comment by spdkils** [comment]
> 
> 
> How does this work with Dank though?

Dank has it's own sort button that still works. But I forgot it does overlap there. The author has suggested they would add the ability to move the sort buttons, but it doesn't support it yet.

I installed it, and still prefer it over no sort buttons at all on iron chests.

**Comment by mahjerion** [comment]
Ah I think the problem with sort buttons and dank is that sometimes duping can occur. I'll have to test this. Thanks for the suggestion!

**Comment by YoItSoul** [comment]
Since it isn't closed and I would like to not duplicate suggestions, any type of sorting would be beautiful on the iron chests.

I'm a bit OCD, but I think others can appreciate it as well!

**Comment by mahjerion** [comment]
Yeah I'm still considering how I'd do this!

**Comment by Zarepheth** [comment]
I installed it, and it helps with sorting - and with transferring many items at once. But there is a problem with Dank. Within the GUI, the Dank sort button overlaps the Inventory Profiles sort buttons, but only the Dank sort button actually works. It's a bit difficult to click just the Dank button without also clicking the Inventory Profiles buttons behind it.

I've not come across any duplication, but Dank comes with a warning about using other mods' sorting features within its own inventories. Apparently, Dank does something with Stack Sizes that messes up most other mods' sorting logic.

**Comment by mahjerion** [comment]
Yes Dank is the primary reason i'm hesitant to add this. But I've been considering removing Dank as it is quite buggy and doesn't seem like it will be fixed anytime soon

**Comment by mahjerion** [comment]
added

**Comment by Zarepheth** [comment]
Dank does have some nice stuff - they can be carried around like backpacks, and include auto-fill options. Further, within the Dank storage, stack sizes can be much, much larger. Which means fewer trips to and from one's base.

But, yeah, Dank doesn't always play nice with other mods.
