### ISSUE TITLE
[BUG] The bottom talent tree is broken (and disconnected from the rest)

### ISSUE THREAD

**Issue by YoItSoul** [mahjerion/Craft-to-Exile-Harmony#43]
- Craft to Exile Version [e.g. 1.3.6]
 - World Type [Multiplayer]
 - RAM Allocation [8GB]

**Describe the bug**
The talent tree connection on the bottom is completely gone. Trying to select one throws an error server side.

**To Reproduce**
1. Go to 'H'
2. Click on 'Talent tree'
3. Select the bottom tree start.
4. See error when trying to select the successive talents.

**Expected behavior**
You cannot select the successive talents from the bottom tree.

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/54139289/101302344-fd8d8d80-3800-11eb-966f-6f7012210079.png)

**Comment by YoItSoul** [comment]
I'd guess that there's a config for ops to use to re-assign the order that's missing, but it's a bug from vanilla non the less.

**Comment by YoItSoul** [comment]
Update: I re-uploaded all of the files to the server and it appears that it's still not working unfortunately. Is there any way to troubleshoot what files are specifically affecting us?

**Comment by mahjerion** [comment]
the talent tree is read from a csv -> json file. not sure what's going on here and I can't seem to recreate this issue hmm
