### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by beeger33** [mahjerion/Craft-to-Exile-Harmony#44]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - RAM Allocation [e.g. 12GB]

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

Placing a crafting table and then opening

**Expected behavior**

 it produces Copper to Silver Chest upgrades for free for some reason

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
fixed in next version, but if you want to fix downgrade iron chests mod
