### ISSUE TITLE
[BUG] Infinite Copper to Silver Chest upgrades

### ISSUE THREAD

**Issue by TheDeathLord3** [mahjerion/Craft-to-Exile-Harmony#45]
**Technical Specs (please complete the following information):**
 - Craft to Exile [Harmony] Version 1.3.6
 - World Type singleplayer
 - RAM Allocation 4GB

**Describe the bug**
When you put nothing into a crafting table, you can craft copper to iron chest upgrades

**To Reproduce**
1. Craft a crafting table
2. Place the crafting table
3. Open the crafting gui

**Expected behavior**
your not suppose to turn nothing into something

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/32182659/101399693-aaf5b500-3884-11eb-8cdb-cb3fcbd43e34.png)

**Comment by mahjerion** [comment]
#44 already been reported and answered, thanks for the detail though
