### ISSUE TITLE
[MOD] Advanced Hook Launchers

### ISSUE THREAD

**Issue by Bioxide123** [mahjerion/Craft-to-Exile-Harmony#46]
Mods link
https://www.curseforge.com/minecraft/mc-mods/advanced-hook-launchers

**Why you think it might be beneficial to Craft to Exile**
I believe this mod would be beneficial to craft to exile harmony because it would bring a new way of traversing hill areas easier and bring new ways of combat mentioning the mod allows hooking enemies
**Additional context**
Reason i want this mod is because i live on a hill and im to lazy to build stairs it would make it easier and more fun to use a grappling hook instead of block climbing

**Comment by mahjerion** [comment]
thanks for the suggestion, we actually do have grappling hook but i've disabled them. I can look into reenabling them.

**Comment by Zarepheth** [comment]
I re-enabled the Campanion grappling hook. Makes things much easier for getting around.

If you don't want to wait for @mahjerion and you are comfortable messing with the modpack's script files, these changes should re-enable the grappling hook.

For REI, change this line `kubejs\startup_scripts\script.js`:
```javascript
event.hide('campanion:grappling_hook')
```
to this:
```javascript
// event.hide('campanion:grappling_hook')
```

And in the `kubejs\data\campanion\recipes\grappling_hook.json` file, change this line:
```json
  "result": {
    "item": "minecraft:air"
  }
```
to this:
```json
  "result": {
    "item": "campanion:grappling_hook"
  }
```
