### ISSUE TITLE
multiple issues i have

### ISSUE THREAD

**Issue by Yomamasnuggets** [mahjerion/Craft-to-Exile-Harmony#47]
I cannot find any of the ward blocks.  I have explored for 6 hours in survival and afterwards loaded a world in creative/spectator and searched for 3 hrs opening dungeon chests and breaking crates.  I also checked the bumblezone, 5 bastions and 3 nether fortresses as well as multiple end cities and end mineshafts and found none.  I therefore cannot complete the quest for them in the book.  

I also had to search through 5 fortresses to find one that was not mostly spawned in bedrock and had a portal.  This may just be my issue im not sure but wanted to bring it up.

**Comment by mahjerion** [comment]
Hm, i thought that i added them to the dark dungeon spawner profiles but apparently they aren't really working. i'll find an alternative way to find them - thanks
