### ISSUE TITLE
[MOD EDIT] - Age of Exile: Config for Spell casting button

### ISSUE THREAD

**Issue by YoItSoul** [mahjerion/Craft-to-Exile-Harmony#48]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/age-of-exile

**Why you think it might be beneficial to Craft to Exile**
If you are using shields or go to read a book, you may accidentally just cast a volcano and melt all of the cows around you. 
Definitely not from experience... RIP cows.

**Additional context**
Just adding the option the change the key bind would be awesome, thanks!

**Comment by mahjerion** [comment]
Great suggestion - the mod author (not me btw) actually has changed this for a future update. It's pretty large and won't be coming out soon though. I can look into backporting it, but it is fixed for later!!!
