### ISSUE TITLE
[BUG]  java.lang.UnsupportedOperationException when I try to modify datapacks

### ISSUE THREAD

**Issue by hvdklauw** [mahjerion/Craft-to-Exile-Harmony#5]
**Technical Specs (please complete the following information):**
 - Craft to Exile - Harmoney Version: 1.1.0b
 - World Type: Singleplayer
 - RAM Allocation: 8Gb

**Describe the bug**
Minecraft crashes when I try to create a new world and edit datapacks

**To Reproduce**
1. Go to Singleplayer
2. Click on Create New World
3. Click on Data Packs
4. Crashes

**Expected behavior**
I expect to see the datapacks, but loading them seems to be the issue.

**Additional Information (screen shots, etc.)**
[crash-2020-09-29_14.54.56-client.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/5299133/crash-2020-09-29_14.54.56-client.txt)

**Comment by mahjerion** [comment]
Yeah you can't use that button, you need to paste them in manually in the folders
