### ISSUE TITLE
[MOD] Ice And Fire

### ISSUE THREAD

**Issue by KovekA** [mahjerion/Craft-to-Exile-Harmony#50]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons

**Why you think it might be beneficial to Craft to Exile**
I think this could help to the RPG style as it contains many fantasy creatures like dragons.

**Additional context**
This mod is for 1.16.4 so i dont know if it will work in 1.16.2, please notify me if it does if you test it.

**Comment by mahjerion** [comment]
also also forge only
