### ISSUE TITLE
[MOD] Astral Sorcery

### ISSUE THREAD

**Issue by KovekA** [mahjerion/Craft-to-Exile-Harmony#51]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/astral-sorcery

**Why you think it might be beneficial to Craft to Exile**
This mod ais based on magic from the stars, its a  good mod and it has a smooth progress.

**Additional context**
its from 1.16.4

**Comment by mahjerion** [comment]
also forge only!
