### ISSUE TITLE
[MOD] Minecolonies

### ISSUE THREAD

**Issue by KovekA** [mahjerion/Craft-to-Exile-Harmony#52]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/minecolonies

**Why you think it might be beneficial to Craft to Exile**
I have been using this mod for a long time and it is a great way to just take some time and relax from the fights, in this mod you can create your own village! It is a really fun mod and it also has some raids that can happen when you got a bigger village.

**Additional context**
from 1.16.4

**Comment by mahjerion** [comment]
forge only :P
