### ISSUE TITLE
[MOD] Crawl

### ISSUE THREAD

**Issue by Smearfo** [mahjerion/Craft-to-Exile-Harmony#53]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/crawl

**Why you think it might be beneficial to Craft to Exile**
It's just a small mod that adds slightly more functionality to the game's crawl ability, so players can do it on keypress instead of needing things like trapdoors. There isn't much else to it besides that.

**Comment by mahjerion** [comment]
Seen this a bunch. Not really sure... how I feel about it. I guess it's pretty cool and Fabric-only. I'll test it out xD

**Comment by mahjerion** [comment]
Probably won't add as it's not entirely necessary haha thanks for the suggestion though
