### ISSUE TITLE
Balance Issues - non-Boss mobs with boss level hitpoints and ability to insta-kill the player.

### ISSUE THREAD

**Issue by Zarepheth** [mahjerion/Craft-to-Exile-Harmony#54]
**Is your feature request related to a problem? Please describe.**
I keep running into mobs whose hit points are 10-20 times or more than my own. I consume half my weapon's durability in a single encounter with such mobs. I might expect this from Bosses, but not from "normal" mobs.

Such extra tough Wither Skeletons can instant kill me, when at full health, if I fail to block fast enough with my shield - despite armor and hit points at level 25-26. Even if I block with my shield, the shield loses half of its durability before killing the mob - if I'm lucky and it doesn't break!

The Nether is filled spiders. If they were near my own level and hit-points, that would be fine; but the sheer quantity of spiders with 10-20 times my hit points (or that of the typical spider), is making Nether exploration impossible.

I run into over-powered mobs in the Overworld, but the frequency of such in the Nether is significantly larger. Even in the Overworld, getting ganged up by two or more such mobs is almost certain death. In the Nether, even one can kill me - and I often have to deal with multiple such mobs.

**Describe the solution you'd like**
Fewer overpowered mobs. A configuration setting to adjust their frequency. A way to know that mobs are extra powerful while still far enough away to avoid notice or to setup traps and fortifications.

**Describe alternatives you've considered**
So far, I've left the Nether and resumed overworld exploration, gaining a couple more levels before going back to the Nether.

Better teleportation options - specifically cross-dimensional teleport, might help. Although, with all the repair work I have to do, I'm running out of iron and gold to for the repair station. For some reason, I've not yet crafted a Waystation, though I've found one in each of two Overworld Villages. I've also noticed a lack of scrolls I normally associate with that mod.

I'd work more on the "Art of Alchemy: Memoriam" mod progression, but I'm stymied at the point where I must find or create polished basalt. To my knowledge, I will only find basalt in the Nether, and thus far, I've not been able to explore far enough to reach a biome or structure with basalt. I've not yet crafted a Modification Station, as it requires an ingredient I have not yet found - I believe it is a drop from a boss mob.

**Additional context**
My first play-through of "Craft to Exile". So I might be going about this wrong. I've attached screenshots of my stats and progression.

I chose the "Ascendant" path.
I just reached level 26.

Character stats:
![2020-12-22_15 23 36](https://user-images.githubusercontent.com/22124796/102934950-c3f88b80-446a-11eb-85d2-6208e06ebe9e.png)
![2020-12-22_15 23 42](https://user-images.githubusercontent.com/22124796/102934952-c4912200-446a-11eb-9858-352b6925ab51.png)
![2020-12-22_15 23 45](https://user-images.githubusercontent.com/22124796/102934954-c4912200-446a-11eb-8330-405aad3ee040.png)
![2020-12-22_15 23 47](https://user-images.githubusercontent.com/22124796/102934955-c529b880-446a-11eb-8389-d417e0014f87.png)
![2020-12-22_15 23 50](https://user-images.githubusercontent.com/22124796/102934956-c529b880-446a-11eb-9ebf-eacfea7ad149.png)

I've been splitting my Skills into Fire and Ice. More on the Ice Path. I've reached "Regenerative Shell", but Instant Kill hits bypass the auto-cast mechanism.
![2020-12-22_15 23 59](https://user-images.githubusercontent.com/22124796/102934957-c5c24f00-446a-11eb-8909-8b7ca4a7b499.png)
![2020-12-22_15 24 09](https://user-images.githubusercontent.com/22124796/102934958-c5c24f00-446a-11eb-89e7-b7a9cc162169.png)

On the Talent map, I started to the left and after getting the basic elemental resistances and increasing my fire and ice skills, crossed over to the top to further enhance my fire and ice abilities.
![2020-12-22_15 24 22](https://user-images.githubusercontent.com/22124796/102934960-c5c24f00-446a-11eb-8764-138b1322354e.png)

**Comment by secondfry** [comment]
Seems like Nether area level is just +15 levels from your current level which results in quite strong mobs. Only way to deal with them I've found so far is shield making Berserker ascendancy worthless. Could be my misunderstanding of core modpack principles tho.

**Comment by Zarepheth** [comment]
I've recently progressed from Level 26 to Level 27, primarily through Overworld spelunking in an abandoned mine near (and under) my base.

I've also created the Modification Station, after summoning a Corrupted Golem and defeating it. I had to make two attempts - I started the first in the middle of the day but as night fell, other mobs got in the way, allowing the golem to regenerate health. When I returned the next morning, it was gone. I summoned the next one in a confined space where it couldn't touch me, but I could attack from range with spells, or from just out of its targeting range with my melee weapon. Despite my positional advantage, it took quite a while to overcome its regenerative powers and defeat it. The Corrupted Golem's hit points, before regeneration, were about 20% higher than the extra-tough mobs in the Nether and about 20 times greater than my own. This would be expected from a Boss mob.

As for the Nether's level, I thought the Nether was for level 20 and up. And I'm beyond level 20. I've not yet attempted the End, which I think is for level 40 and up...

**My Gear - (lots of screenshots)**
I haven't upgraded my gear for a while. The Epic, Legendary, and Mythic gear of lower level have better affixes (and frequently other stats) than common items from my own level. Unfortunately, I'm not yet high enough level for some of the better gear I've acquired...
No screenshot for my ranged weapon. I typically use the mage weapon and spells for ranged attacks, skipping the Bow or Crossbow.

_Note_: I've chosen mage-related attributes, skills, and talents - but my gear might be better suited for other character types.

Head:
![2020-12-23_00 10 00-Head](https://user-images.githubusercontent.com/22124796/102966277-32fad200-44b5-11eb-9079-ed6172f92895.png)

Torso 1:
![2020-12-23_00 10 48](https://user-images.githubusercontent.com/22124796/102966469-8a00a700-44b5-11eb-8254-a885112b2c51.png)

Torso 2 (to avoid Piglin aggression):
![2020-12-23_00 10 08-Torso-2](https://user-images.githubusercontent.com/22124796/102966318-47d76580-44b5-11eb-8a01-e292633a7a0c.png)

Legs:
![2020-12-23_00 10 11](https://user-images.githubusercontent.com/22124796/102966378-64739d80-44b5-11eb-8fee-64b88472b375.png)

Feet:
![2020-12-23_00 10 12](https://user-images.githubusercontent.com/22124796/102966387-689fbb00-44b5-11eb-969f-d5bfce2f213f.png)

Necklace:
![2020-12-23_00 10 15](https://user-images.githubusercontent.com/22124796/102966421-76edd700-44b5-11eb-8eb1-b8734b77d628.png)

Ring 1:
![2020-12-23_00 10 17](https://user-images.githubusercontent.com/22124796/102966428-79503100-44b5-11eb-8714-040460f8500d.png)

Ring 2:
![2020-12-23_00 10 19](https://user-images.githubusercontent.com/22124796/102966432-7bb28b00-44b5-11eb-9957-21647b748317.png)

Shield:
![2020-12-23_00 10 24](https://user-images.githubusercontent.com/22124796/102966440-7f461200-44b5-11eb-9812-607b224faadd.png)

Melee Weapon:
![2020-12-23_00 10 26](https://user-images.githubusercontent.com/22124796/102966450-83722f80-44b5-11eb-9b56-424c38290687.png)

Mage Weapon:
![2020-12-23_00 10 29](https://user-images.githubusercontent.com/22124796/102966456-866d2000-44b5-11eb-880c-25edb44b6ade.png)

**Comment by secondfry** [comment]
I would advise to roll the gear of your appropriate level (meaning that you will craft lots of gear pieces hoping for them to roll good). In case you get common base, you should either use Orb of Transformation of it (it you don't have much resources) or Crystal of Truth (in case you are diving in riches you may also consider using Stone of Hope).
This will net you appropriate level gear with good affixes.

Then consider socketing your gear with Crown of Discovery and runes or gems. For example you can socket your gear with 4 runes – CEN-DOS-ANO-TOQ which will cap you for ele resist even tho lowering the maximum a little. Notice that you can socket these runes into gear on any level, it just has to have 4 sockets. ![](https://i.imgur.com/cE1VjIj.png)

Then repeat the same process with jewelry and weapon.

In case you still won't deal enough damage, maybe consider lowering the variety of scrolls you are using – like focus on fire damage only.

I hope this should help.

**Comment by Zarepheth** [comment]
Should I be going for Cloth, Leather, or Metal as my armor? It appears that each benefits different defensive stats, but I'm not really sure how they relate to my play style.

For instance, cloth seems to improve Magic Shield, which regenerates quickly (but can still be destroyed and take a few seconds to come back). Leather improves dodge, but do I have to be moving to enjoy the benefits of dodge? Metal improves armor and health; I assume that means the Minecraft typical armor, which reduces incoming damage and I assume the health grants me additional hit points.

I'd prefer to strike mobs, from a distance, with spells. But when facing more than one typical mob of my own level, I generally run out of mana before finishing them off. And attacking from a distance means keeping a barrier between me and them - or running and casting - hoping I don't fall into a hole, or get stuck...

**Comment by secondfry** [comment]
I've yet to check datapacks to see what kind of affixes roll on what type of gear, but logically spellcasters should make cloth (for spell power and ES [magic shield]).

AFAIK you don't have to be moving to enjoy dodge benefits, but that needs to be checked (either ingame or maybe here or in support Discord).

I myself was using metal for armor and Berserker for melee, but later switched to cloth and RF (righteous fire). Almost everything what I've encountered so far is dying before RF aura expires (I wish it would never expire like in PoE).

**Comment by mahjerion** [comment]
Mob difficulty can definitely be adjusted, but I think you lack defensive stats. You have good resistances for the most part, but where is your HP? You didn't take any HP nodes but you have HP gear. I think you should either go cloth and get some Magic Shield nodes, or dive into the left tree and take more HP nodes. You are going almost pure DPS :O

**Comment by Zarepheth** [comment]
@mahjerion 
Thanks for the recommendation. Although, unless I use some reset potions, it might take a few levels to apply them. (Maybe I _should_ use some reset potions, they don't seem too expensive...)

I just made level 30 - which means I should revisit my gear. The suggestion by @secondfry helped. Although, lack of appropriate resources meant I couldn't upgrade all my gear, only some of it.

I've been focusing on damage, in the hopes I can kill mobs in 2 or 3 hits, instead of 20 or 30 hits. At the moment, mobs in the 150-300 hp range can be killed with basic ice ball or fire ball in 2 or 3 hits, but the occasional mob with 10 times the hit points can fully drain my mana before they are dead. Having multiple such mobs without a safe structure to protect me becomes rather stressful, even in the overworld.

**Comment by Zarepheth** [comment]
This may deserve a different issue, but what good are Crystals of Truth compared with Orbs of Transforming? In both cases, they merely convert my "common" gear into "magical" gear. Yet the Crystals of Truth are much more expensive, and much rarer as drops. (Yes, the description claims that Crystals of Truth should convert "common" to "rare"; but so far they've only converted my "common" to "magical".)

Also, what good are Crystals of Purification? I haven't found a use for them. It seems that "sealed" gear is best unsealed with Tomes of Identification. It would be nice if I could revert those Crystals of Purification back to Crystals of Truth - then I could use them for Dank Storage.

Speaking of storage, the lack of consistent sorting in the Iron Chests is sufficiently annoying that I'm using normal chests, or the occasional Dank storage. But with Dank storage, going from level 2 to 3 is harder than level 3 to 4. At least with the mob drops and salvage I've been getting. 

And moving on to Salvage, I occasionally come across gear that says "Unsalvageable". I can't salvage it, it takes up space, it's usually not as good as the gear I already have, yet I'd like to use it instead of trashing it.

**Comment by secondfry** [comment]
Sorting is fixed by using "Inventory Profiles" client mod. It also add a lot of QoL improvements (quality of life improvements, i.e. stacking items from inventory to chest).

Sealed gear is not unidentified gear. IIRC you can find that gear is sealed by holding Ctrl.

Also, yes, Crystals of Truth seems to be broken.

**Comment by Zarepheth** [comment]
Thanks, @secondfry; I installed Inventory Profiles, which provides nicer sorting - similar to the original Inventory Tweaks. It also has a few inventory shifting features like Quark.

But it's sorting buttons interfere with the Dank sorting button. Despite that, it does work with Iron Chests!

**Comment by mahjerion** [comment]
Great feedback.

"(Yes, the description claims that Crystals of Truth should convert "common" to "rare"; but so far they've only converted my "common" to "magical".)" seems like a bug, I can look into it.

but yeah @secondfry is correct. I'll also be adding inventory profiles and likely removing dank sometime in the future

gonna close this now!
