### ISSUE TITLE
[MOD] Dynamic Music

### ISSUE THREAD

**Issue by LudoCrypt** [mahjerion/Craft-to-Exile-Harmony#55]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/dynamic-music

**Why you think it might be beneficial to Craft to Exile**
I feel as though this mod will benefit Craft to Exile as this modpack has my other music mod, Music Duration Reducer, and a good ambient environment Is a good playing experience, and I feel like Dynamic Music does that well. Both of these mods together I feel create a magical playing experience.

**Additional context**
N/A

**Comment by mahjerion** [comment]
Looks great, thanks for suggestions. I'll keep this in mind for a later update.

**Comment by mahjerion** [comment]
Actually gonna pass on this one. I like the expanded selection but not how it plays certain music depending on environment
