### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lvPokka** [mahjerion/Craft-to-Exile-Harmony#56]
**Describe the bug**
[15:34:25] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fatxporbs requires {fabricloader @ [>=0.10.6]}

**To Reproduce**
CrafttoExile-Harmony-1.3.5 +1 Server failed to start

**Comment by mahjerion** [comment]
update to 1.3.8, server files avail on discord
