### ISSUE TITLE
Dank 2 to Dank 3 upgrade is more expensive than Dank 3 to Dank 4.

### ISSUE THREAD

**Issue by Zarepheth** [mahjerion/Craft-to-Exile-Harmony#57]
**Is your feature request related to a problem? Please describe.**
Specifically, the Dank 2 to Dank 3 upgrade requires 4 _Orbs of Disorder_, which are relatively rare drops and require _T3 Salvaged Dust_ to craft. The Dank 3 to Dank 4 upgrade requires 4 "_Crystals of Truth_" and four _Emerald Blocks_. Although the _Emerald Blocks_ might appear to be the limiting factor, I've acquired many emeralds from loot chests, mob drops, and Emerald Ore (my base is near a Skyris Mountain biome, which has caves and mines tunneling under it). A "_Crystal of Truth_" can be crafted with _T2 Salvaged Dust_ dust, making it much cheaper than crafting an _Orb of Disorder_. My limiting factor for upgrading my Dank 2s to Dank 3s is the lack of sufficient _Salvaged Dust_. It takes 729 _T0 Salvaged Dust_ to produce a single _T3 Salvaged Dust_, but only 81  _T0 Salvaged Dust_ to make  _T2 Salvaged Dust_.

**Describe the solution you'd like**
Cheaper recipe for "Orbs of Disorder", or perhaps swap the Orbs of Disorder with the Crystals of Truth in the Dank 3 and Dank 4 recipes.

**Describe alternatives you've considered**
So far, I've created additional Dank 2s. I've not yet acquired the resources to upgrade more than 1 to Dank 3 or higher (it's currently at Dank 4 and I'm close to upgrading to Dank 5 - the Diamond Blocks are my limiting factor).

**Comment by mahjerion** [comment]
Huh, thanks. I can swap these around.
