### ISSUE TITLE
[BUG] XP Gains are bugged with /team command.

### ISSUE THREAD

**Issue by Kamisoi** [mahjerion/Craft-to-Exile-Harmony#59]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 1.3.9b
 - World Type Multiplayer

**Describe the bug**
A clear and concise description of what the bug is:
There seems to be issue with players nearby in Minecraft /team that they only get 1xp per hostile mob kill. Issue was found on Meowstard's Community Server and reported by players to admins, but since they don't change even one bit in config files, seems like modpack issue.

**To Reproduce**
1. Get into party with other player on same level
2. Try farming mobs
3. ???
4. No profit :d

**Expected behavior**
A clear and concise description of what you expected to happen:
Players should be given proper amount of XP.

**Comment by mahjerion** [comment]
It seems to happen randomly.. not really sure what's causing it. I'll take a better look at the source code and see possibilities

**Comment by mahjerion** [comment]
This happens because the exp being split gets cast as an integer, which floors the value. So if you gain 3.9 exp between 4 people, it's split as 0.975 exp which gets floored to 0.

**Comment by mahjerion** [comment]
probably fixed for next update
