### ISSUE TITLE
[BUG] Missing Wool Tarp recipe

### ISSUE THREAD

**Issue by metanchik** [mahjerion/Craft-to-Exile-Harmony#6]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [1.1.0c]
 - World Type [multiplayer]
 - RAM Allocation [8GB]

**Describe the bug**
Wool Tarp (Campanion mod) doesn't have a recipe

**Comment by mahjerion** [comment]
It does, it's 3 wool on the bottom and shears in the middle

**Comment by Zarepheth** [comment]
The recipe does not appear in the Roughly Enough Items (REI) recipes list.

**Comment by heyjudek** [comment]
> The recipe does not appear in the Roughly Enough Items (REI) recipes list.

It didn't appear for me either, until I put wool and shears in the way mahjerion described and suddenly it's there :)

**Comment by michaelslec** [comment]
I am also having this problem

**Comment by mahjerion** [comment]
it doesnt appear, but it works - its hardcoded
