### ISSUE TITLE
[BUG] Some mods wrong version

### ISSUE THREAD

**Issue by machond** [mahjerion/Craft-to-Exile-Harmony#60]
Hi, some mods from modpack (client) harmony requires 1.16.2 when trying run on 1.16.4 (example xp-storage).

Could you update mods files?

Best, M!

**Comment by mahjerion** [comment]
come to discord the updated server files are on discord

**Comment by machond** [comment]
Yeah, server is fine from discord, but my client wont start because
checking of each mod version. On curse there More update version for
example for XP storage.

wt., 5 sty 2021, 19:50 użytkownik mahjerion <notifications@github.com>
napisał:
