### ISSUE TITLE
[BUG] Gravestone location for lag / performance optimization

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#61]
This will be a repository of grave locations that need to be manually removed. Please make sure to post coordinates as they are seen, making sure to include appropriate positive and negative denomination.

-112, 66, -282
-113, 66, -285
-47, 71, -445
-23, 77, -462
-47, 71, -445
150, 72, -271
739, 63, -503
225, 64, -1137
225, 64, -1138
219, 39, -1084

**Comment by ProvoGo** [comment]
-112, 66, -282
-113, 66, -285
-47, 71, -445
-23, 77, -462
-47, 71, -445
150, 72, -271
739, 63, -503
225, 64, -1137
225, 64, -1138
219, 39, -1084 

Have all been removed

**Comment by mahjerion** [comment]
You guys are great, thank you! I'll keep this up incase there are more (which I'm sure there are)
