### ISSUE TITLE
[BUG] Quest '' stay away '' can not be completed

### ISSUE THREAD

**Issue by CodeNameYue** [mahjerion/Craft-to-Exile-Harmony#62]
Craft to Exile Version 2.0.1-alpha-fix
World Type singleplayer and multiplayer
RAM Allocation 4 GB

Quest '' stay away'' cannot be completed by crafting iron hammer

**Comment by mahjerion** [comment]
its already fixed thanks

**Comment by CodeNameYue** [comment]
I'm playing on the version 2.0.1 alpha fix and I still cannot complete it.

**Comment by CodeNameYue** [comment]
> its already fixed thanks (for the release)

I'm playing on the version 2.0.1 alpha fix and I still cannot complete it.

**Comment by mahjerion** [comment]
Alpha is not release.
