### ISSUE TITLE
BYG / Certain BetterEnd and BetterNether Items not generating Gear Stats

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#64]
Due to the inherent nature of Pendorite and Ametrine "upgrading" their counterparts of Netherite items (which also upgrade from Diamond), Craft to Exile stats do not regenerate or populate the items. 

For example: Diamond-tier Sword has stats from level range 15-25. When the sword is upgraded to Netherite, the name stays as "Diamond Sword", all stats stay the same, and the only thing that changes is the durability. This pattern continues when upgrading to Pendorite from Netherite (haven't tried Ametrine, but I assume it is the same).

Secondly, while Terminite, Aeternium, and Crystalite armor sets have corresponding Gear Levels, their weapons and tools do not (other than Aeternium Hammer).

The Aeternium tool/weapon crafting recipe, which deviates from vanilla-style, may cause this to be problematic?

**Comment by mahjerion** [comment]
Thanks for write-up. Aeternium/terminite/crystalkite dont have gear levels because of a typo and should be easily fixed. Pendorite and ametrine, netherite, cincinnasite-diamond, and probably crystalite will need to be reworked probably becuase they all "upgrade"

**Comment by mahjerion** [comment]
fix ed
