### ISSUE TITLE
Healing Wave - Holy Talent tree

### ISSUE THREAD

**Issue by darkt1981** [mahjerion/Craft-to-Exile-Harmony#68]
**Is your feature request related to a problem? Please describe.**
Holy Tree - Healing Wave this healing spell doesnt scale in power even at max level the heal is so low even with the +30% increase of pacifist, compaired to other heals.

After more testing with the =30% heal increase the spell heals for 10 hp xD

**Describe the solution you'd like**
Maybe increase the heal, to behonest i might need a 40-50% increase if it is a direct heal.

**Describe alternatives you've considered**
or even beter make it a heal over time aura effect maybe? with a a 5 -15s duration depending on the skill point added, if so it still might need a 15-25 % increase in heal power.  ?

**Additional context**
If you make it a heal over time, maybe change holy - Bravery aura to Health regen to life steal increase ?

**Comment by mahjerion** [comment]
hi see comment on other issue :P repost this or reference it in dissonacne issue tracker if youd like
