### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by darkt1981** [mahjerion/Craft-to-Exile-Harmony#69]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.8.5c
 - All
 - 10GB

**Describe the bug**
Ocean tree talent Frost Shield, doesnt ally shield to team mates, only to the user it self.

**To Reproduce**
Just cast it next to someone.

**Expected behavior**
Shoulkd apply on your self and teammates and add a magic shield to you and them.

**Additional Information (screen shots, etc.)**
Testing it in /teams and in /slash party, teammate didnt get it try to spam cast it to see if it was lag but still no go.

**Comment by mahjerion** [comment]
yo you posted thiso n the wrong issue tracker, this is for harmony
