### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TriggerPT** [mahjerion/Craft-to-Exile-Harmony#7]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [1.1.0c]
 - World Type [singleplayer]
 - RAM Allocation [e.g. 6GB]

**Describe the bug**
When running a specific console command /setspawn the game crashes

**To Reproduce**
1.New world / cheats On
2.Enter game
3.Run command in console: /sethome with successfull outcome
4.Run command in console /setspawn and returns exception
5. return to game
6.Run command in console /setspawn and returns exception again

**Expected behavior**
Command should be sucessfull

**Additional Information (screen shots, etc.)**

**Comment by TriggerPT** [comment]
[crash-2020-10-02_18.20.34-server.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/5321356/crash-2020-10-02_18.20.34-server.txt)

**Comment by mahjerion** [comment]
Hmm you'll probably be better off posting this in commands mod issue tracker tbh... there's nothing else to the setspawn command? it worked fine for me
