### ISSUE TITLE
[BUG] All-Knowing Runeword is not functioning as expected

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#70]
The All-Knowing Runeword is supposed to add +X to all stats, however this trait does not work. The item takes on +STR, +DEX, and +INT from the runes individually, which works, however the +All Attributes, while appearing to work as such on the character sheet, does not actually produce any higher stats when taking into consideration mana (WIS), Magic Shield (WIL) or Health (VIT). I assume that, while STR/DEX/INT are modified by the runes, this is the only calculation that is taken into consideration, not including the +All increment..

**Comment by mahjerion** [comment]
Any idea if it is ONLY runewords that this happens?

**Comment by mahjerion** [comment]
I've changed thisi for the next update so that anything using all attributes doesnt use it anymore, I believe all attributes isn't working?

**Comment by Raspyutin** [comment]
I believe it is a bug with All attributes, yes. Each individual attribute works as intended. Maybe changing it to + to each individual attribute would fix the error.

**Comment by Raspyutin** [comment]
With All-Knowing changed to +STR/DEX/INT, this seems to be working as intended.
