### ISSUE TITLE
[BUG] Quest: Eternal Pillar cannot be mined

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#72]
One of the quests requires an Eternal Pillar to be in one's inventory; however, at this time, neither the Eternal Pillar or the Eternal Portal frame can be crafted and/or mined.

**Comment by mahjerion** [comment]
Don't they appear naturally in the end? It says in the guide for dummies

**Comment by Raspyutin** [comment]
Sorry for the late response - They do appear naturally, but the quest requires one in your inventory, not to just encounter one. I'll check this out again and update to see if it's fixed.

**Comment by mahjerion** [comment]
You'd have to break it and have it in inventory to complete the quest - this was my intention. Is it not possible?
