### ISSUE TITLE
When dieing with a bed set you still spawn in spawn town.

### ISSUE THREAD

**Issue by darkt1981** [mahjerion/Craft-to-Exile-Harmony#73]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.8.6 (and before)

**Describe the bug**
When you die in a dream dimesniuon even with a bed set you get tped to spawn when you die.

**To Reproduce**
1. goto a dream dimension and just die xD

**Expected behavior**
Spawn in your own bed

**Additional Information (screen shots, etc.)**
none

**Comment by mahjerion** [comment]
this is harmony issue tracker, wrong one! go to https://github.com/mahjerion/Craft-to-Exile-Dissonance/issues
