### ISSUE TITLE
crash starting new world

### ISSUE THREAD

**Issue by mistythecat** [mahjerion/Craft-to-Exile-Harmony#74]
[crash-2021-02-08_16.06.06-server.txt](https://github.com/mahjerion/Craft-to-Exile-Harmony/files/5944929/crash-2021-02-08_16.06.06-server.txt)

**Comment by mahjerion** [comment]
Are you on LAN?

**Comment by ItphingsMonk** [comment]
I'm having the same issue, I use lan. Well what ever the default settings and mode is when playing single-player, with no external server. I downloaded it from the forge site and created instance with MultiMC. It crashes when starting a new world. After it reaches 100%. Dissonance pack works for me fine. I can upload my crash report if you need to.

**Comment by mahjerion** [comment]
Don't play on LAN, causes issues

**Comment by ItphingsMonk** [comment]
How do you make sure not to play lan? By playing off-line mode on multiMC mode? Or is there an option ingame?

**Comment by mahjerion** [comment]
@ItphingsMonk You host a dedicated server, and then people can join as if you were doing lan, it's basically the same thing
