### ISSUE TITLE
[BUG] Nether doesn't work no more

### ISSUE THREAD

**Issue by WhiteNightDragon** [mahjerion/Craft-to-Exile-Harmony#75]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.0.2d
 - World Type multiplayer
 - RAM Allocation 2.25

**Describe the bug**
Before updating the server to 2.0.2d the nether was working fine. But one day wanting to go to the nether fortress to get more blaze rods I go to the waystone to teleport to there since I place one there since the nether fortress was very far where the portal is at. It didn't work so I thought I have to go to the portal first to fixed that portal. Yeah the portal didn't work, so i made a new portal somewhere far and it still didn't work. Went to check the server setting (don't own but a co-owner to get the server up and restart) there a checkmark on the nether is it is available. Please help I really want to go farming in the nether.

**Comment by mahjerion** [comment]
You'll need to fix your level.dat. recreat a new world using the same seed the copy the level.dat from the new world over

**Comment by mahjerion** [comment]
GOnna close this because that is the fix for it!
