### ISSUE TITLE
[BUG] cursed spawners frequently not progressing

### ISSUE THREAD

**Issue by cainamar** [mahjerion/Craft-to-Exile-Harmony#76]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.0.2e
 - World Type singleplayer
 - RAM Allocation 4GB

**Describe the bug**
the cursed spawners found in one structure type tend to not progress, despite no more mobs remaining nearby

**To Reproduce**
it seems somewhat random but it happens more often than not when trying to clear the waves

**Expected behavior**
waves to progress as normal and receive the bonus crate at the end (which has only managed to happen once so far)

**Additional Information (screen shots, etc.)**
not sure which mod adds these but they seem to be tailored to the modpack given they drop the AoE chests at the end

if I had to guess what causes it, it could either be from mobs killing each other or if one of the waves is creepers and they explode instead of being killed by the player

edit: I had some more successful attempts and found the ward blocks dropping too, so it's clear the drops have been edited for the pack

**Comment by mahjerion** [comment]
It's a known issue, i blieve there's already an issue opened regarding this, and I have even posted to the mod that adds these spawners.

**Comment by mahjerion** [comment]
It's called Dark Dungeons on curseforge

**Comment by mahjerion** [comment]
ive done a lot to alleviat  this, looks like no fix from mod side tho
