### ISSUE TITLE
[FEEDBACK] nether either overtuned or the questbook needs updated info

### ISSUE THREAD

**Issue by cainamar** [mahjerion/Craft-to-Exile-Harmony#77]
**Is your feature request related to a problem? Please describe.**
 questbook suggests nether exploration at level 15 while mobs there are still significantly harder at even a higher level (currently 28)

**Describe the solution you'd like**
either for the nether enemies to be nerfed or the questbook to reflect the actual suggested level/difficulty

**Describe alternatives you've considered**
I had tried going to the nether earlier, got almost immediately one-shot by a mage, and decided to come back later

wasn't immediately one-shot but the enemies' levels still seemed much higher than mine

**Additional context**
I saw this previous post here: https://github.com/mahjerion/Craft-to-Exile-Harmony/issues/54
but there's no mention of what the questbook says, so I guess I'm just at a loss for what's intended
the nether looks really fun to explore in this pack but it's rather painful in its current state in terms of enemy scaling

**Comment by mahjerion** [comment]
I think it's a bug where nether mobs are higher level than they should be, is that basically what's happening? Or are they the same level, just really hard?

**Comment by cainamar** [comment]
most of the mobs have the "???" where the level indicator is, but I recall seeing at least one mob at level 31 or so? and I even remember seeing one that could've been leveled appropriately but it was outnumbered by the higher level ones and wasn't difficult

I could try flying around in spectator to get a better overview because I didnt stay in there very long after I accidentally hit a zombie piglin and got like two shotted

**Comment by mahjerion** [comment]
Weird, not sure why it's happening but that's def a bug. I'll double check

**Comment by cainamar** [comment]
just wanted to update, the end seems overtuned/bugged in the same way: all the endermen were ??? leveled andthe dragon had 29k health and one-shot me, despite me being at level 34 and the questbook suggesting level 30

**Comment by mahjerion** [comment]
Interesting, that does help! I think I might know what's causing this!

**Comment by mahjerion** [comment]
I FIXED THIS!
