### ISSUE TITLE
[FEEDBACK]

### ISSUE THREAD

**Issue by navybofus** [mahjerion/Craft-to-Exile-Harmony#78]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The addition of our server to the pack's Official Server list.

**Describe alternatives you've considered**
Modpack page post with self-promotion, and self-promotion channel in the official Discord. However, neither of these seemed appropriate so I thought I should ask here first.

**Additional context**
None

**Comment by mahjerion** [comment]
PM me about this stuff, haha
