### ISSUE TITLE
[BUG] can't socket an item with a free socket slot

### ISSUE THREAD

**Issue by cainamar** [mahjerion/Craft-to-Exile-Harmony#79]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.0.2e
 - World Type sp
 - RAM Allocation 4gb

**Describe the bug**
attempting to socket a gem or rune into an item with a free socket (created with a crown of discovery) will not work in the socketing station

**To Reproduce**
1. crafted a shield
2. used a crown of discovery on the shield to gain a socket slot
3. attempt to socket the empty slot

**Expected behavior**
for the gem/rune to socket

**Additional Information (screen shots, etc.)**
the item in question: 
![image](https://user-images.githubusercontent.com/53030836/107803514-b061f680-6d30-11eb-9ba6-844d174502d7.png)

there's also no "requirements not met" disclaimer when hovering over the item in the socketing station
and the shield should be of appropriate level for the rune/gem I've tried to socket so far
I've successfully used a runeword in a shield before as well, so I don't know if it has to do with the base item

**Comment by mahjerion** [comment]
is it consistent with all items? o.o

**Comment by cainamar** [comment]
..... nevermind I was using the gear modifying station lmao

**Comment by mahjerion** [comment]
LOL nice
