### ISSUE TITLE
[MOD] Create

### ISSUE THREAD

**Issue by KovekA** [mahjerion/Craft-to-Exile-Harmony#80]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/create

**Why you think it might be beneficial to Craft to Exile**
I saw the mod and I think its really cool, so it would be nice if you add it.

**Additional context**
nope

**Comment by mahjerion** [comment]
Appreciate it but create is A FORGE mod, we are on fabric

**Comment by KovekA** [comment]
Ops, I ment to post this on the another modpack, sorry
