### ISSUE TITLE
[BUG] Storage Options quest

### ISSUE THREAD

**Issue by goldern** [mahjerion/Craft-to-Exile-Harmony#81]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version: 2.0.2e
 - World Type: singleplayer
 - RAM Allocation: 8 Gb

**Describe the bug**
Dank 1 is not being detected in the quest "Storage Options"

**To Reproduce**
1. Craft "Dank 1"
2. See quest "Storage Options"
3. See error

**Expected behavior**
It should detect the newly crafted Dank 1 and update the progress from 0/1 to 1/1.

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/5741155/107883816-f99c7c80-6ecf-11eb-9799-8100af28c9f0.png)
![image](https://user-images.githubusercontent.com/5741155/107883830-0faa3d00-6ed0-11eb-970b-4dd5cff7c3e9.png)

**Comment by mahjerion** [comment]
not sure why this is happening, only seems to happen sometimes, is it on the offiical server?

**Comment by goldern** [comment]
It's in a singleplayer world.
