### ISSUE TITLE
[BUG] Waila Settings/Plugin Settings Crash

### ISSUE THREAD

**Issue by goldern** [mahjerion/Craft-to-Exile-Harmony#82]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version: 2.0.2e
 - World Type: singleplayer
 - RAM Allocation: 8 Gb

**Describe the bug**
Crash when entering Waila's "Waila Settings" or "Plugin Settings" 

**To Reproduce**
1. Press "0" key
2. Click on "Plugin Settings"
3. It will crash

**Expected behavior**
Unbind key "0" from opening Waila configs.

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/5741155/107883854-3c5e5480-6ed0-11eb-8d42-1d6caef6fdff.png)
Crash if you click "Waila Settings" or "Plugin Settings".

**Comment by mahjerion** [comment]
this is fixed in the next update! thanks for reporting
