### ISSUE TITLE
[BUG] Charm recipes not in oredictionary

### ISSUE THREAD

**Issue by goldern** [mahjerion/Craft-to-Exile-Harmony#83]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version: 2.0.2e
- World Type: singleplayer
- RAM Allocation: 8 Gb

**Describe the bug**
Charm items do not work in some recipes.

**To Reproduce**
1. Craft "Oak Barrel" without changing recipe to the minecraft default recipe, it will create a Charm Oak Barrel
2. Try to craft the recipes that use Oak Barrel, none will work with the Charm Oak Barrel

**Expected behavior**
Oredictionary all charm items with the default version craft.

**Additional Information (screen shots, etc.)**
![image](https://user-images.githubusercontent.com/5741155/107883922-ab3bad80-6ed0-11eb-819a-99672e622e19.png)
![image](https://user-images.githubusercontent.com/5741155/107883999-28ffb900-6ed1-11eb-8b06-5174ccf0d2dd.png)
![image](https://user-images.githubusercontent.com/5741155/107884005-3026c700-6ed1-11eb-980a-8e7fd1f98b40.png)

**Comment by Raspyutin** [comment]
As a heads up, if you are stuck with this, the workaround is to create a Minecraft barrel with 2 different types of wood. This will make a non-Charm barrel. You probably already figured this out, but for anyone else who is struggling with creating a Dank, this may help.
