### ISSUE TITLE
[MOD] Polymorph (Fabric): Choose crafting result when recipes conflict

### ISSUE THREAD

**Issue by navybofus** [mahjerion/Craft-to-Exile-Harmony#85]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Why you think it might be beneficial to Craft to Exile**
Several recipes conflict, and there is no management mod (Craftweaker) to fix them manually. IMO, leaving the recipes alone and using a mod like Polymorph, takes the strain out of server management (including SP) 

**Additional context**
![image](https://i.ibb.co/TkWswkG/polymorph.gif)

**Comment by mahjerion** [comment]
We have polymorph o.o

**Comment by navybofus** [comment]
Sorry Mahj, I just realized that the server pack from curse forge didn't have it in there. I FTP'd it up to the server and it's all working now. Thanks for clearing that up!
