### ISSUE TITLE
[MOD]Mining Dimensions 

### ISSUE THREAD

**Issue by Eridrost** [mahjerion/Craft-to-Exile-Harmony#86]
**Link the Mod's CurseForge page**
Paste the link here.
https://www.curseforge.com/minecraft/mc-mods/mining-dimensions-fabric

**Why you think it might be beneficial to Craft to Exile**
A clear and concise explanation of your reasons.
I think that a mining dimension would be great so we don't destroy our main world. I also think that other dimensions would have their own benefits. I am an admin on a server that uses your modpack, we require multiple dimensions to balance the game.
**Additional context**

**Comment by navybofus** [comment]
This would be great for persistent overworlds on servers, As server admins, we've been scratching our heads trying to find a way to add a dimension where players can mine and dungeon without tearing up the overworld (where everyone lives).

**Comment by mahjerion** [comment]
good suggestion, i'll look into incorporating this sometime

**Comment by OrbitalBiomes** [comment]
Also one of the server admins trying to figure this out.  Thank you for considering this.  
What you have created here for us is awesome!  And it is great to have a developer like you who will take the time and listen.
Thank you very much!

**Comment by mahjerion** [comment]
not going to add this for harmony but liekly for next pack. thanks
