### ISSUE TITLE
[BUG] Repeatable quests not repeatable

### ISSUE THREAD

**Issue by cbat007** [mahjerion/Craft-to-Exile-Harmony#88]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
      - latest version
 - World Type [e.g. singleplayer/LAN/multiplayer]
      - Multiplayer
 - RAM Allocation [e.g. 4GB]
      - Im not sure i can get more info later

**Describe the bug**
A clear and concise description of what the bug is;

In the quest book the Overworld quest section has 4 repeatable quests in the upper right side. Normally upon completion these can be done again relativly soon, however, my brother has had his say resetting in 150 days and never going down, he hasnt been able to compete them beyond once. I dont know all the details of specs and all, but i can get what info you might need, just putting this out there to see if anyone is having the same issue.

**To Reproduce**

**Expected behavior**

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
to confirm you're not playing lan right? The repeatable quests are very very buggy for some reason.. i hope its fixed eventually by shedaniel (HQM mod). will keep this issue open for now

**Comment by cbat007** [comment]
I believe he isnt, i sent a message to him about this from the other posts and i havent gotten a response; ill make sure he isnt then get back to you

**Comment by cbat007** [comment]
Ok he said he joined and left a party in the quest book a couple times and that cleared it up, he ws not on LAN so im not sure where the issue was.
