### ISSUE TITLE
[BUG] Recipe for 4x Crimson Gems and 1x Ghast Tear is blank

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#89]
Just looking in JEI, I see that there is no "product" for the recipe requiring 4x crimson gems and 1x ghast tear. The other weapons seem to be functioning as intended, however.

**Comment by mahjerion** [comment]
I removed this myself it's not a bug

**Comment by mahjerion** [comment]
Althoug hI guess its sort of buggy that it's appearing still lol
