### ISSUE TITLE
[BUG] No recipe for sandwiches 

### ISSUE THREAD

**Issue by Blizhazard** [mahjerion/Craft-to-Exile-Harmony#9]
**Technical Specs**
 - Craft to Exile Version [1.1.0c]
 - World Type [singleplayer]
 - RAM Allocation [4GB]

**Describe the bug**
There is no available REI recipe for sandwiches from the common expansion: foodstuffs mod. Could be because there are multiple different combinations of sandwich fillings.

**Comment by mahjerion** [comment]
you're right there's no recipe because of the combinations. I believe there's a book you need to craft or something that shows you how to do it.
