### ISSUE TITLE
[BUG] Thallasium Ore (Better End) not in Worldgen index

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#91]
It looks like there is a database including Thallasium ore for all armor / weapons (Level 1-50) for all weapons and tools, however it looks like the Hammer is not included. Also - there is no Worldgen information for Thallasium, indicating that the ore is not in the game.

**Comment by mahjerion** [comment]
I think this is introduced newly by BetterEnd, and probably isn't fully implemented yet

**Comment by Raspyutin** [comment]
Ok, sorry to reopen / revisit this, but this is actually breaking the Quest progression, as, in order to craft Aeternium ingots (needed for Aeternium pickaxe crafting for quests), one must use the End Stone Smelter. The End Stone Smelter requires 4x Thallasium ingots to craft, meaning there is no craftable way to get Aeternium tools.
