### ISSUE TITLE
[BUG] New Anvils (Thallasium -> Terminite -> Aeternium) and End Stone Smelter

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#92]
As Thallasium is not included in the worldgen, this recipe is assumed to be broken, as it requires Thallasium ingots and blocks.

**Comment by Raspyutin** [comment]
This is further an issue, as it seems that the Better End tools may require their respective anvils to craft now (Aeternium at least)

**Comment by mahjerion** [comment]
What is Thallasium? o.o

**Comment by Raspyutin** [comment]
Although Thallasium isn't implemented, I don't believe it will hinder anything at the moment. Issue closed.
