### ISSUE TITLE
[BUG] Crafting Quest still bugged (Pendorite)

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#95]
Nether Quest - Pendora is still broken, as it requires the crafting of a Pendorite Axe, Pickaxe, and Battleaxe, however these milestones are not completed when crafting Pendorite items, still. Not sure if the quest is linked to the "wrong" version of Pendorite tools - IE the tools that need to be upgraded, rather than crafted.

Old version (upgraded) Pendorite tools in inventory do not trigger requirements for this quest, either.

**Comment by mahjerion** [comment]
Fixed in next update!
