### ISSUE TITLE
[BUG] The talent tree Mana damage talent

### ISSUE THREAD

**Issue by cbat007** [mahjerion/Craft-to-Exile-Harmony#96]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version [e.g. 2.2.5b]
 - latest
 - World Type [e.g. singleplayer/LAN/multiplayer]
 - multiplayer
 - RAM Allocation [e.g. 4GB]
 - idk

**Describe the bug**
I got the talent that reduces your heath magic shield and dodge chance i believe those three and its supposed to divert 50 percent of damage to mana; however, i never seem to notice my mana take any of the damage away. 

**To Reproduce**

**Expected behavior**

**Additional Information (screen shots, etc.)**

**Comment by mahjerion** [comment]
Thanks, will check out

**Comment by mahjerion** [comment]
fixed for next update prob
