### ISSUE TITLE
[MOD] MC dungeons Weapons mod

### ISSUE THREAD

**Issue by Bigmeat-enlargedflesh** [mahjerion/Craft-to-Exile-Harmony#97]
**Link the Mod's CurseForge page**
https://www.curseforge.com/minecraft/mc-mods/mcdw?page=7#c26

**Why you think it might be beneficial to Craft to Exile**
This is a mod that basically brings a nice variety of weapons from the minecraft RPG game "Minecraft dungeons." 
It adds a nice diversity of weapons both ranged and melee with some having some interesting effects (For example one of the spears can penetrate through large hordes of mobs) and personally I feel like a mod based off of an RPG version of minecraft would fit very well with the mod that makes minecraft on its own an RPG. 
there are some weapons that can be used for elemental uniques, such as the frost scythe and the poisonous glaive

**Additional context**

**Comment by mahjerion** [comment]
I do think the MC Dungeons mods by Chronos are really cool. They will take some time for testing and I know that there are a few issues currently with them. Maybe in the future.
