### ISSUE TITLE
[FEEDBACK]

### ISSUE THREAD

**Issue by Clugor** [mahjerion/Craft-to-Exile-Harmony#98]
![crimson](https://user-images.githubusercontent.com/79830485/109464272-a96eff80-7a23-11eb-8896-7aa94afcad4f.png)

Seems like crimson moons have a very high spawn rate of slimes as opposed to other creatures. Loot sucks from slimes so it kinda feels like crimson moons aren't worth trying to farm and better to just afk in a house until it's over.

Maybe tone down their spawning on crimson moons?

**Comment by mahjerion** [comment]
Wow, that's brutal. I can't change the spawn rate unfortauntely, not sure why it picks the slimes so often though

**Comment by mahjerion** [comment]
not much i can do unfort.
