### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Restlen** [mahjerion/Craft-to-Exile-Harmony#99]
- Craft to Exile Dissonance Version 2.9.0b
 - World Type  singleplayer
 - RAM Allocation  8GB

**Describe the bug**
Visual bug on. Looking at quest. it is blocked and cant be seen due to a overlay problem.

**To Reproduce**
1. Go to quest
2. Click on or highlight a quest. they are block or cant be seen due to the overlay problem

**Expected behavior**
to see it clearly or not be blocked
**Additional Information (screen shots, etc.)**
![2021-03-01_09 29 10](https://user-images.githubusercontent.com/79857872/109519256-afd79880-7a70-11eb-9b2c-62a3b04c880d.png)
![2021-03-01_09 29 21](https://user-images.githubusercontent.com/79857872/109519264-b239f280-7a70-11eb-8d6e-85e3cd9e24ab.png)

**Comment by mahjerion** [comment]
You posted this on the wrong modpack issue tracker. But if you go to dissonance you'll see that this has been answered many times - it's a known bug and nothing i can do :P
